// 공통 데이터 (번역, 증상 목록, 응급 규칙)은 기존과 동일하게 유지하고, Session Storage 헬퍼를 추가합니다.

const translations = {
    ko: {
    arm_left_upper: "왼쪽 위팔",
    arm_left_elbow: "왼쪽 팔꿈치",
    arm_left_lower: "왼쪽 아래팔",
    arm_left_wrist: "왼쪽 손목",
    arm_left_hand: "왼쪽 손",
    arm_right_upper: "오른쪽 위팔",
    arm_right_elbow: "오른쪽 팔꿈치",
    arm_right_lower: "오른쪽 아래팔",
    arm_right_wrist: "오른쪽 손목",
    arm_right_hand: "오른쪽 손",

    time_p1: "1교시",
    time_p2: "2교시",
    time_p3: "3교시",
    time_p4: "4교시",
    time_lunch: "점심시간",
    time_p5: "5교시",
    time_p6: "6교시",
    time_before: "학교오기 전",
    time_days: "며칠 전",
    follow_trauma: "어떻게 다쳤나요?",
    trauma_friend: "친구랑 장난치다",
    trauma_alone: "혼자 넘어짐/부딪힘",
    trauma_sports: "체육시간/운동하다가",

        arm_left_all: "왼쪽 팔 전체", arm_right_all: "오른쪽 팔 전체",
        arm_left_multi: "왼쪽 팔 여러 부위", arm_right_multi: "오른쪽 팔 여러 부위",
        arm_left_mid: "왼쪽 팔꿈치·아랫팔", arm_right_mid: "오른쪽 팔꿈치·아랫팔",
        arm_left_bot: "왼쪽 손·손목", arm_right_bot: "오른쪽 손·손목",
        belly_all: "복부 전체",
        belly_top_all: "윗배 전체",
        belly_bottom_all: "아랫배 전체",
        belly_left_top: "왼쪽 윗배",
        belly_right_top: "오른쪽 윗배",
        belly_left_bottom: "왼쪽 아랫배",
        belly_right_bottom: "오른쪽 아랫배",
        pain_1: "통증 1",
        pain_2: "통증 2",

      lang_name: "한국어", step_0_title: "언어를 선택하세요.", step_1_title: "어디가 아파요?", step_2_title: "어떻게 아파요?", step_3_title: "얼마나 아파요?", step_4_title: "언제부터 아파요?", step_5_title: "이대로 보낼까요?",
      btn_prev: "이전", btn_next: "다음", btn_submit: "맞아요 (보내기)", btn_restart: "다른 곳도 아파요",
      quick_1: "다쳤어요", quick_2: "배가 아파요", quick_3: "머리가 아파요", quick_4: "열이 나요", quick_5: "코피가 나요", quick_6: "토할 것 같아요",
      front: "앞모습", back: "뒷모습", idk: "잘 모르겠어요",
      part_head: "머리", part_eye: "눈", part_ear: "귀", part_nose: "코", part_mouth: "입·이", part_neck: "목",
      part_chest: "가슴", part_belly: "배", part_arm: "팔·손", part_leg: "다리·발", part_back: "등·허리", part_skin: "피부", part_whole: "몸 전체",
      side_select_arm: "어느 쪽 팔이에요?", side_select_leg: "어느 쪽 다리예요?", side_left: "왼쪽", side_right: "오른쪽", side_both: "양쪽 다",
      belly_top: "윗배", belly_navel: "배꼽 주변", belly_bottom: "아랫배", belly_right_bottom: "오른쪽 아래",
      arm_upper: "어깨·윗팔", arm_lower: "팔꿈치·아랫팔", arm_hand: "손·손목",
      leg_thigh: "허벅지", leg_knee: "무릎", leg_calf: "종아리·발목", leg_foot: "발",
      hurt_how: "어떻게 다쳤어요?", hurt_state: "지금 상태는요?",
      hurt_1: "넘어짐", hurt_2: "부딪힘", hurt_3: "베임", hurt_4: "접질림",
      state_1: "피가 나요", state_2: "부었어요", state_3: "멍들었어요", state_4: "움직이면 아파요",
      head_q: "어지럽거나 토할 것 같아요?", yes: "네", no: "아니요",      follow_belly: "밥을 먹었어요?", follow_fever: "약을 먹었어요?", follow_vomit: "몇 번 토했어요?",
      vomit_1: "1번", vomit_2: "2번", vomit_3: "3번 이상",
      allergy_title: "알레르기가 있어요?", allergy_none: "없어요", allergy_drug: "약", allergy_peanut: "땅콩/견과류", allergy_milk: "우유", allergy_egg: "계란", allergy_seafood: "해산물", allergy_peach: "복숭아", allergy_wheat: "밀가루",        med_title: "먹고 있는 약이 있나요?", med_none: "안 먹어요", med_cold: "감기약", med_pain: "진통제", med_digest: "소화제", med_hospital: "병원/처방약", med_idk: "잘 모르겠어요", summary_med_info: "💊 복용 중인 약", summary_med_label: "복용 약",
      
        allergy_voice: "기타(직접 말하기)",
      nurse_mode: "보건교사 모드", pin_prompt: "비밀번호를 입력하세요:", no_records: "접수된 문진표가 없습니다.", delete: "삭제", summary_title: "AI 요약 내용", error_api: "요약 생성 중 오류가 발생했습니다.",
      summary_symptom: "증상", summary_part: "부위", summary_symptom_label: "증상", summary_pain: "통증 정도", summary_time: "시작 시간", summary_allergy_info: "🏥 알레르기 정보", summary_allergy_label: "알레르기",
      pain_min: "안 아파요", pain_max: "너무 아파요", btn_start_over: "새로 작성하기",
      popup_success: "전달 완료!", popup_desc: "선생님께 전달되었습니다.", belly_chest: "가슴", profile_title: "내 정보 입력", profile_grade: "학년", profile_class: "반", profile_number: "번호", profile_name: "이름", profile_placeholder: "입력", profile_next: "다음으로"
    },
    en: {
    arm_left_upper: "Left Upper Arm",
    arm_left_elbow: "Left Elbow",
    arm_left_lower: "Left Forearm",
    arm_left_wrist: "Left Wrist",
    arm_left_hand: "Left Hand",
    arm_right_upper: "Right Upper Arm",
    arm_right_elbow: "Right Elbow",
    arm_right_lower: "Right Forearm",
    arm_right_wrist: "Right Wrist",
    arm_right_hand: "Right Hand",

    time_p1: "1st Period",
    time_p2: "2nd Period",
    time_p3: "3rd Period",
    time_p4: "4th Period",
    time_lunch: "Lunch Time",
    time_p5: "5th Period",
    time_p6: "6th Period",
    time_before: "Before School",
    time_days: "A Few Days Ago",
    follow_trauma: "How did you get hurt?",
    trauma_friend: "Playing with friend",
    trauma_alone: "Fell/bumped alone",
    trauma_sports: "During PE/Sports",

        arm_left_all: "Entire left arm", arm_right_all: "Entire right arm",
        arm_left_multi: "Multiple left arm parts", arm_right_multi: "Multiple right arm parts",
        arm_left_mid: "Left elbow/forearm", arm_right_mid: "Right elbow/forearm",
        arm_left_bot: "Left hand/wrist", arm_right_bot: "Right hand/wrist",
        belly_all: "Entire belly",
        belly_top_all: "Entire upper belly",
        belly_bottom_all: "Entire lower belly",
        belly_left_top: "Upper left belly",
        belly_right_top: "Upper right belly",
        belly_left_bottom: "Lower left belly",
        belly_right_bottom: "Lower right belly",
        pain_1: "Pain 1",
        pain_2: "Pain 2",

        lang_name: "English", step_0_title: "Choose your language.", step_1_title: "Where does it hurt?", step_2_title: "How does it hurt?", step_3_title: "How much does it hurt?", step_4_title: "When did it start?", step_5_title: "Is this correct?",
        btn_prev: "Previous", btn_next: "Next", btn_submit: "Submit", btn_restart: "Add other symptoms",
        quick_1: "I am hurt", quick_2: "Stomachache", quick_3: "Headache", quick_4: "Fever", quick_5: "Nosebleed", quick_6: "Feel like vomiting",
        front: "Front", back: "Back", idk: "I don't know",
        part_head: "Head", part_eye: "Eyes", part_ear: "Ears", part_nose: "Nose", part_mouth: "Mouth/Teeth", part_neck: "Neck",
        part_chest: "Chest", part_belly: "Belly", part_arm: "Arm/Hand", part_leg: "Leg/Foot", part_back: "Back", part_skin: "Skin", part_whole: "Whole body",
        side_select_arm: "Which arm?", side_select_leg: "Which leg?", side_left: "Left", side_right: "Right", side_both: "Both",
        belly_top: "Upper belly", belly_navel: "Around navel", belly_bottom: "Lower belly", belly_right_bottom: "Right lower belly",
        arm_upper: "Shoulder/Upper arm", arm_lower: "Elbow/Lower arm", arm_hand: "Hand/Wrist",
        leg_thigh: "Thigh", leg_knee: "Knee", leg_calf: "Calf/Ankle", leg_foot: "Foot",
        hurt_how: "How did you get hurt?", hurt_state: "How is it now?",
        hurt_1: "Fell down", hurt_2: "Bumped", hurt_3: "Cut", hurt_4: "Sprained",
        state_1: "Bleeding", state_2: "Swollen", state_3: "Bruised", state_4: "Hurts when moving",
        head_q: "Do you feel dizzy or feel like vomiting?", yes: "Yes", no: "No",        follow_belly: "Did you eat?", follow_fever: "Did you take medicine?", follow_vomit: "How many times did you vomit?",
        vomit_1: "1 time", vomit_2: "2 times", vomit_3: "3 or more times",
        allergy_title: "Do you have any allergies?", allergy_none: "None", allergy_drug: "Medicine", allergy_peanut: "Peanuts/Nuts", allergy_milk: "Milk", allergy_egg: "Eggs", allergy_seafood: "Seafood", allergy_peach: "Peach", allergy_wheat: "Wheat",
        med_title: "Are you taking any medication?", med_none: "None", med_cold: "Cold medicine", med_pain: "Painkiller", med_digest: "Digestive medicine", med_hospital: "Prescription", med_idk: "I don't know", summary_med_info: "💊 Current Medication", summary_med_label: "Medication",        med_title: "Are you taking any medication?", med_none: "None", med_cold: "Cold medicine", med_pain: "Painkiller", med_digest: "Digestive medicine", med_hospital: "Prescription", med_idk: "I don't know", summary_med_info: "💊 Current Medication", summary_med_label: "Medication",
      
        allergy_voice: "Other (speak)",
        nurse_mode: "Nurse Mode", pin_prompt: "Enter PIN:", no_records: "No records found.", delete: "Delete", summary_title: "AI Summary", error_api: "Error generating summary.",
        summary_symptom: "Symptom", summary_part: "Part", summary_symptom_label: "Symptoms", summary_pain: "Pain Level", summary_time: "Start Time", summary_allergy_info: "🏥 Allergy Info", summary_allergy_label: "Allergies",
        pain_min: "No pain", pain_max: "Worst pain", btn_start_over: "Start over",
        popup_success: "Successfully Sent!", popup_desc: "It has been sent to the teacher.", belly_chest: "Chest", profile_title: "Enter Profile", profile_grade: "Grade", profile_class: "Class", profile_number: "Number", profile_name: "Name", profile_placeholder: "Type here", profile_next: "Next"
    },
    zh: {
    arm_left_upper: "左上臂",
    arm_left_elbow: "左手肘",
    arm_left_lower: "左前臂",
    arm_left_wrist: "左手腕",
    arm_left_hand: "左手",
    arm_right_upper: "右上臂",
    arm_right_elbow: "右手肘",
    arm_right_lower: "右前臂",
    arm_right_wrist: "右手腕",
    arm_right_hand: "右手",

    time_p1: "第一节课",
    time_p2: "第二节课",
    time_p3: "第三节课",
    time_p4: "第四节课",
    time_lunch: "午餐时间",
    time_p5: "第五节课",
    time_p6: "第六节课",
    time_before: "上学前",
    time_days: "几天前",
    follow_trauma: "是怎么受伤的？",
    trauma_friend: "跟朋友玩闹",
    trauma_alone: "自己摔倒/撞到",
    trauma_sports: "体育课/运动时",

        arm_left_all: "整个左臂", arm_right_all: "整个右臂",
        arm_left_multi: "左臂多个部位", arm_right_multi: "右臂多个部位",
        arm_left_mid: "左手肘/前臂", arm_right_mid: "右手肘/前臂",
        arm_left_bot: "左手/手腕", arm_right_bot: "右手/手腕",
        belly_all: "整个腹部",
        belly_top_all: "整个上腹部",
        belly_bottom_all: "整个下腹部",
        belly_left_top: "左上腹",
        belly_right_top: "右上腹",
        belly_left_bottom: "左下腹",
        belly_right_bottom: "右下腹",
        pain_1: "疼痛 1",
        pain_2: "疼痛 2",

        lang_name: "中文", step_0_title: "请选择语言。", step_1_title: "哪里不舒服？", step_2_title: "怎么不舒服？", step_3_title: "有多痛？", step_4_title: "什么时候开始的？", step_5_title: "这样发送吗？",
        btn_prev: "上一步", btn_next: "下一步", btn_submit: "确认 (发送)", btn_restart: "添加其他症状",
        quick_1: "受伤了", quick_2: "肚子痛", quick_3: "头痛", quick_4: "发烧", quick_5: "流鼻血", quick_6: "想吐",
        front: "正面", back: "背面", idk: "不知道",
        part_head: "头", part_eye: "眼睛", part_ear: "耳朵", part_nose: "鼻子", part_mouth: "嘴/牙齿", part_neck: "脖子",
        part_chest: "胸", part_belly: "肚子", part_arm: "胳膊/手", part_leg: "腿/脚", part_back: "背/腰", part_skin: "皮肤", part_whole: "全身",
        side_select_arm: "哪只胳膊？", side_select_leg: "哪条腿？", side_left: "左边", side_right: "右边", side_both: "两边都",
        belly_top: "上腹", belly_navel: "肚脐周围", belly_bottom: "下腹", belly_right_bottom: "右下腹",
        arm_upper: "肩膀/上臂", arm_lower: "手肘/前臂", arm_hand: "手/手腕",
        leg_thigh: "大腿", leg_knee: "膝盖", leg_calf: "小腿/脚踝", leg_foot: "脚",
        hurt_how: "怎么受伤的？", hurt_state: "现在怎么样？",
        hurt_1: "摔倒", hurt_2: "撞到", hurt_3: "割伤", hurt_4: "扭伤",
        state_1: "流血", state_2: "肿了", state_3: "瘀青", state_4: "一动就痛",
        head_q: "觉得头晕或想吐吗？", yes: "是", no: "否",        follow_belly: "吃饭了吗？", follow_fever: "吃药了吗？", follow_vomit: "吐了几次？",
        vomit_1: "1次", vomit_2: "2次", vomit_3: "3次以上",
        allergy_title: "有过敏吗？", allergy_none: "没有", allergy_drug: "药物", allergy_peanut: "花生/坚果", allergy_milk: "牛奶", allergy_egg: "鸡蛋", allergy_seafood: "海鲜", allergy_peach: "桃子", allergy_wheat: "小麦",
        med_title: "你在吃什么药吗？", med_none: "没有", med_cold: "感冒药", med_pain: "止痛药", med_digest: "消化药", med_hospital: "处方药", med_idk: "不知道", summary_med_info: "💊 服用药物", summary_med_label: "药物",        med_title: "你在吃什么药吗？", med_none: "没有", med_cold: "感冒药", med_pain: "止痛药", med_digest: "消化药", med_hospital: "处方药", med_idk: "不知道", summary_med_info: "💊 服用药物", summary_med_label: "药物",
      
        allergy_voice: "其他(语音输入)",
        nurse_mode: "护士模式", pin_prompt: "请输入密码:", no_records: "没有记录。", delete: "删除", summary_title: "AI 总结", error_api: "生成总结时出错。",
        summary_symptom: "症状", summary_part: "部位", summary_symptom_label: "症状", summary_pain: "疼痛程度", summary_time: "开始时间", summary_allergy_info: "🏥 过敏信息", summary_allergy_label: "过敏",
        pain_min: "不痛", pain_max: "非常痛", btn_start_over: "重新填写",
        popup_success: "发送成功！", popup_desc: "已经发送给老师。", belly_chest: "胸部", profile_title: "输入信息", profile_grade: "年级", profile_class: "班级", profile_number: "学号", profile_name: "姓名", profile_placeholder: "输入", profile_next: "下一步"
    },
    ru: {
    arm_left_upper: "Левое плечо",
    arm_left_elbow: "Левый локоть",
    arm_left_lower: "Левое предплечье",
    arm_left_wrist: "Левое запястье",
    arm_left_hand: "Левая рука",
    arm_right_upper: "Правое плечо",
    arm_right_elbow: "Правый локоть",
    arm_right_lower: "Правое предплечье",
    arm_right_wrist: "Правое запястье",
    arm_right_hand: "Правая рука",

    time_p1: "1-й урок",
    time_p2: "2-й урок",
    time_p3: "3-й урок",
    time_p4: "4-й урок",
    time_lunch: "Обед",
    time_p5: "5-й урок",
    time_p6: "6-й урок",
    time_before: "До школы",
    time_days: "Несколько дней назад",
    follow_trauma: "Как вы поранились?",
    trauma_friend: "Играл с другом",
    trauma_alone: "Сам упал/ударился",
    trauma_sports: "На физкультуре",

        arm_left_all: "Вся левая рука", arm_right_all: "Вся правая рука",
        arm_left_multi: "Несколько частей левой руки", arm_right_multi: "Несколько частей правой руки",
        arm_left_mid: "Левый локоть/предплечье", arm_right_mid: "Правый локоть/предплечье",
        arm_left_bot: "Левая кисть/запястье", arm_right_bot: "Правая кисть/запястье",
        belly_all: "Весь живот",
        belly_top_all: "Весь верх живота",
        belly_bottom_all: "Весь низ живота",
        belly_left_top: "Верхняя левая часть",
        belly_right_top: "Верхняя правая часть",
        belly_left_bottom: "Нижняя левая часть",
        belly_right_bottom: "Нижняя правая часть",
        pain_1: "Боль 1",
        pain_2: "Боль 2",

        lang_name: "Русский", step_0_title: "Выберите язык.", step_1_title: "Где болит?", step_2_title: "Как болит?", step_3_title: "Насколько сильно болит?", step_4_title: "Когда это началось?", step_5_title: "Всё верно?",
        btn_prev: "Назад", btn_next: "Вперед", btn_submit: "Отправить", btn_restart: "Добавить еще симптомы",
        quick_1: "Я поранился(лась)", quick_2: "Болит живот", quick_3: "Болит голова", quick_4: "Температура", quick_5: "Кровь из носа", quick_6: "Тошнит",
        front: "Спереди", back: "Сзади", idk: "Я не знаю",
        part_head: "Голова", part_eye: "Глаза", part_ear: "Уши", part_nose: "Нос", part_mouth: "Рот/зубы", part_neck: "Шея",
        part_chest: "Грудь", part_belly: "Живот", part_arm: "Рука/кисть", part_leg: "Нога/ступня", part_back: "Спина/поясница", part_skin: "Кожа", part_whole: "Всё тело",
        side_select_arm: "Какая рука?", side_select_leg: "Какая нога?", side_left: "Левая", side_right: "Правая", side_both: "Обе",
        belly_top: "Верх живота", belly_navel: "Вокруг пупка", belly_bottom: "Низ живота", belly_right_bottom: "Внизу справа",
        arm_upper: "Плечо/Предплечье", arm_lower: "Локоть/Предплечье", arm_hand: "Кисть/Запястье",
        leg_thigh: "Бедро", leg_knee: "Колено", leg_calf: "Икра/Лодыжка", leg_foot: "Ступня",
        hurt_how: "Как вы поранились?", hurt_state: "Как сейчас?",
        hurt_1: "Упал(а)", hurt_2: "Ударился(лась)", hurt_3: "Порезался(лась)", hurt_4: "Растяжение",
        state_1: "Идет кровь", state_2: "Опухло", state_3: "Синяк", state_4: "Больно двигать",
        head_q: "Кружится голова или тошнит?", yes: "Да", no: "Нет",        follow_belly: "Вы ели?", follow_fever: "Вы пили лекарство?", follow_vomit: "Сколько раз вас стошнило?",
        vomit_1: "1 раз", vomit_2: "2 раза", vomit_3: "3 или более раз",
        allergy_title: "Есть аллергия?", allergy_none: "Нет", allergy_drug: "Лекарства", allergy_peanut: "Арахис/Орехи", allergy_milk: "Молоко", allergy_egg: "Яйца", allergy_seafood: "Морепродукты", allergy_peach: "Персик", allergy_wheat: "Пшеница",
        med_title: "Вы принимаете какие-либо лекарства?", med_none: "Нет", med_cold: "От простуды", med_pain: "Обезболивающее", med_digest: "Для пищеварения", med_hospital: "По рецепту", med_idk: "Я не знаю", summary_med_info: "💊 Принимаемые лекарства", summary_med_label: "Лекарства",        med_title: "Вы принимаете какие-либо лекарства?", med_none: "Нет", med_cold: "От простуды", med_pain: "Обезболивающее", med_digest: "Для пищеварения", med_hospital: "По рецепту", med_idk: "Я не знаю", summary_med_info: "💊 Принимаемые лекарства", summary_med_label: "Лекарства",
      
        allergy_voice: "Другое (голосом)",
        nurse_mode: "Режим медсестры", pin_prompt: "Введите пароль:", no_records: "Записей нет.", delete: "Удалить", summary_title: "Сводка ИИ", error_api: "Ошибка генерации сводки.",
        summary_symptom: "Симптом", summary_part: "Часть", summary_symptom_label: "Симптомы", summary_pain: "Уровень боли", summary_time: "Время начала", summary_allergy_info: "🏥 Инфо об аллергии", summary_allergy_label: "Аллергии",
        pain_min: "Не болит", pain_max: "Очень больно", btn_start_over: "Начать заново",
        popup_success: "Успешно отправлено!", popup_desc: "Отправлено учителю.", belly_chest: "Грудь", profile_title: "Введите данные", profile_grade: "Класс", profile_class: "Группа", profile_number: "Номер", profile_name: "Имя", profile_placeholder: "Введите", profile_next: "Далее"
    },
    vi: {
    arm_left_upper: "Bắp tay trái",
    arm_left_elbow: "Khuỷu tay trái",
    arm_left_lower: "Cẳng tay trái",
    arm_left_wrist: "Cổ tay trái",
    arm_left_hand: "Bàn tay trái",
    arm_right_upper: "Bắp tay phải",
    arm_right_elbow: "Khuỷu tay phải",
    arm_right_lower: "Cẳng tay phải",
    arm_right_wrist: "Cổ tay phải",
    arm_right_hand: "Bàn tay phải",

    time_p1: "Tiết 1",
    time_p2: "Tiết 2",
    time_p3: "Tiết 3",
    time_p4: "Tiết 4",
    time_lunch: "Giờ ăn trưa",
    time_p5: "Tiết 5",
    time_p6: "Tiết 6",
    time_before: "Trước khi đến trường",
    time_days: "Vài ngày trước",
    follow_trauma: "Bạn bị thương như thế nào?",
    trauma_friend: "Chơi với bạn",
    trauma_alone: "Tự ngã/va đập",
    trauma_sports: "Trong giờ thể dục",

        arm_left_all: "Toàn bộ tay trái", arm_right_all: "Toàn bộ tay phải",
        arm_left_multi: "Nhiều phần tay trái", arm_right_multi: "Nhiều phần tay phải",
        arm_left_mid: "Khuỷu tay/cẳng tay trái", arm_right_mid: "Khuỷu tay/cẳng tay phải",
        arm_left_bot: "Bàn tay/cổ tay trái", arm_right_bot: "Bàn tay/cổ tay phải",
        belly_all: "Toàn bộ bụng",
        belly_top_all: "Toàn bộ bụng trên",
        belly_bottom_all: "Toàn bộ bụng dưới",
        belly_left_top: "Bụng trên bên trái",
        belly_right_top: "Bụng trên bên phải",
        belly_left_bottom: "Bụng dưới bên trái",
        belly_right_bottom: "Bụng dưới bên phải",
        pain_1: "Cơn đau 1",
        pain_2: "Cơn đau 2",

        lang_name: "Tiếng Việt", step_0_title: "Chọn ngôn ngữ của bạn.", step_1_title: "Đau ở đâu?", step_2_title: "Đau như thế nào?", step_3_title: "Đau nhiều không?", step_4_title: "Bắt đầu từ khi nào?", step_5_title: "Như thế này đúng không?",
        btn_prev: "Trước", btn_next: "Tiếp theo", btn_submit: "Gửi", btn_restart: "Thêm triệu chứng khác",
        quick_1: "Bị thương", quick_2: "Đau bụng", quick_3: "Đau đầu", quick_4: "Sốt", quick_5: "Chảy máu cam", quick_6: "Buồn nôn",
        front: "Phía trước", back: "Phía sau", idk: "Không biết",
        part_head: "Đầu", part_eye: "Mắt", part_ear: "Tai", part_nose: "Mũi", part_mouth: "Miệng/Răng", part_neck: "Cổ",
        part_chest: "Ngực", part_belly: "Bụng", part_arm: "Tay", part_leg: "Chân", part_back: "Lưng/Eo", part_skin: "Da", part_whole: "Toàn thân",
        side_select_arm: "Tay nào?", side_select_leg: "Chân nào?", side_left: "Trái", side_right: "Phải", side_both: "Cả hai",
        belly_top: "Bụng trên", belly_navel: "Quanh rốn", belly_bottom: "Bụng dưới", belly_right_bottom: "Dưới bên phải",
        arm_upper: "Vai/Cánh tay trên", arm_lower: "Khuỷu tay/Cẳng tay", arm_hand: "Bàn tay/Cổ tay",
        leg_thigh: "Đùi", leg_knee: "Đầu gối", leg_calf: "Bắp chân/Mắt cá chân", leg_foot: "Bàn chân",
        hurt_how: "Bị thương thế nào?", hurt_state: "Bây giờ thế nào?",
        hurt_1: "Ngã", hurt_2: "Va đập", hurt_3: "Bị cắt", hurt_4: "Bong gân",
        state_1: "Chảy máu", state_2: "Sưng", state_3: "Bầm tím", state_4: "Đau khi cử động",
        head_q: "Có thấy chóng mặt hay buồn nôn không?", yes: "Có", no: "Không",        follow_belly: "Đã ăn chưa?", follow_fever: "Đã uống thuốc chưa?", follow_vomit: "Nôn mấy lần rồi?",
        vomit_1: "1 lần", vomit_2: "2 lần", vomit_3: "3 lần trở lên",
        allergy_title: "Có dị ứng không?", allergy_none: "Không có", allergy_drug: "Thuốc", allergy_peanut: "Đậu phộng/Hạt", allergy_milk: "Sữa", allergy_egg: "Trứng", allergy_seafood: "Hải sản", allergy_peach: "Đào", allergy_wheat: "Lúa mì",
        med_title: "Bạn có đang uống thuốc gì không?", med_none: "Không", med_cold: "Thuốc cảm", med_pain: "Thuốc giảm đau", med_digest: "Thuốc tiêu hóa", med_hospital: "Thuốc kê đơn", med_idk: "Tôi không biết", summary_med_info: "💊 Thuốc đang uống", summary_med_label: "Thuốc",        med_title: "Bạn có đang uống thuốc gì không?", med_none: "Không", med_cold: "Thuốc cảm", med_pain: "Thuốc giảm đau", med_digest: "Thuốc tiêu hóa", med_hospital: "Thuốc kê đơn", med_idk: "Tôi không biết", summary_med_info: "💊 Thuốc đang uống", summary_med_label: "Thuốc",
      
        allergy_voice: "Khác (nói trực tiếp)",
        nurse_mode: "Chế độ y tá", pin_prompt: "Nhập mật khẩu:", no_records: "Không có hồ sơ.", delete: "Xóa", summary_title: "Tóm tắt AI", error_api: "Lỗi tạo tóm tắt.",
        summary_symptom: "Triệu chứng", summary_part: "Bộ phận", summary_symptom_label: "Các triệu chứng", summary_pain: "Mức độ đau", summary_time: "Thời gian bắt đầu", summary_allergy_info: "🏥 Thông tin dị ứng", summary_allergy_label: "Dị ứng",
        pain_min: "Không đau", pain_max: "Rất đau", btn_start_over: "Làm lại từ đầu",
        popup_success: "Gửi thành công!", popup_desc: "Đã được gửi cho giáo viên.", belly_chest: "Ngực", profile_title: "Nhập thông tin", profile_grade: "Khối", profile_class: "Lớp", profile_number: "Số", profile_name: "Tên", profile_placeholder: "Nhập", profile_next: "Tiếp theo"
    },
    ja: {
    arm_left_upper: "左上腕",
    arm_left_elbow: "左肘",
    arm_left_lower: "左前腕",
    arm_left_wrist: "左手首",
    arm_left_hand: "左手",
    arm_right_upper: "右上腕",
    arm_right_elbow: "右肘",
    arm_right_lower: "右前腕",
    arm_right_wrist: "右手首",
    arm_right_hand: "右手",

    time_p1: "1時間目",
    time_p2: "2時間目",
    time_p3: "3時間目",
    time_p4: "4時間目",
    time_lunch: "昼休み",
    time_p5: "5時間目",
    time_p6: "6時間目",
    time_before: "学校に来る前",
    time_days: "数日前",
    follow_trauma: "どうやって怪我をしましたか？",
    trauma_friend: "友達とふざけていて",
    trauma_alone: "一人で転んだ/ぶつけた",
    trauma_sports: "体育/運動中",

        belly_all: "お腹全体",
        belly_top_all: "上腹部全体",
        belly_bottom_all: "下腹部全体",
        belly_left_top: "左上腹部",
        belly_right_top: "右上腹部",
        belly_left_bottom: "左下腹部",
        belly_right_bottom: "右下腹部",
        pain_1: "痛み 1",
        pain_2: "痛み 2",

        lang_name: "日本語",
        step_0_title: "ことばをえらんでね",
        step_1_title: "どこがいたいですか？",
        step_2_title: "どんなふうにいたいですか？",
        step_3_title: "どのくらいいたいですか？",
        step_4_title: "いつからいたいですか？",
        step_5_title: "これでいいですか？",
        btn_prev: "もどる",
        btn_next: "つぎへ",
        btn_submit: "はい (おくる)",
        btn_restart: "ほかのところもいたい",
        quick_1: "けがをした",
        quick_2: "おなかがいたい",
        quick_3: "あたまがいたい",
        quick_4: "ねつがある",
        quick_5: "はなぢがでた",
        quick_6: "きもちわるい",
        front: "まえ",
        back: "うしろ",
        idk: "わからない",
        part_head: "あたま",
        part_eye: "め",
        part_ear: "みみ",
        part_nose: "はな",
        part_mouth: "くち・は",
        part_neck: "くび",
        part_chest: "むね",
        part_belly: "おなか",
        part_arm: "うで・て",
        part_leg: "あし",
        part_back: "せなか・こし",
        part_skin: "ひふ",
        part_whole: "からだぜんたい",
        side_select_arm: "どっちのうでですか？",
        side_select_leg: "どっちのあしですか？",
        side_left: "ひだり",
        side_right: "みぎ",
        side_both: "りょうほう",
        belly_top: "おなかのうえ",
        belly_navel: "おへそのまわり",
        belly_bottom: "おなかのした",
        belly_right_bottom: "みぎした",
        arm_upper: "かた・にのうで",
        arm_lower: "ひじ・うで",
        arm_hand: "て・てくび",
        leg_thigh: "ふともも",
        leg_knee: "ひざ",
        leg_calf: "ふくらはぎ・あしくび",
        leg_foot: "あし",
        hurt_how: "どうやってけがをしましたか？",
        hurt_state: "いまはどんなかんじですか？",
        hurt_1: "ころんだ",
        hurt_2: "ぶつけた",
        hurt_3: "きった",
        hurt_4: "ひねった",
        state_1: "ちがでている",
        state_2: "はれている",
        state_3: "あおあざができている",
        state_4: "うごかすといたい",
        head_q: "めまいがしたり、きもちわるかったりしますか？",
        yes: "はい",
        no: "いいえ",        follow_belly: "ごはんはたべましたか？",
        follow_fever: "おぐすりはのみましたか？",
        follow_vomit: "なんかいもどしましたか？",
        vomit_1: "1かい",
        vomit_2: "2かい",
        vomit_3: "3かい以上",
        allergy_title: "アレルギーはありますか？",
        allergy_none: "ない",
        allergy_drug: "おぐすり",
        allergy_peanut: "ピーナッツ・ナッツ",
        allergy_milk: "ぎゅうにゅう",
        allergy_egg: "たまご",
        allergy_seafood: "シーフード",
        allergy_peach: "もも",
        allergy_wheat: "こむぎ",
        med_title: "飲んでいる薬はありますか？", med_none: "飲んでいません", med_cold: "かぜ薬", med_pain: "痛み止め", med_digest: "胃腸薬", med_hospital: "病院の薬", med_idk: "わかりません", summary_med_info: "💊 服用中の薬", summary_med_label: "服用薬",
        arm_left_all: "左うで全体", arm_right_all: "右うで全体", arm_left_mid: "左ひじ・前うで", arm_right_mid: "右ひじ・前うで", arm_left_bot: "左手・手首", arm_right_bot: "右手・手首", arm_left_multi: "左うで複数", arm_right_multi: "右うで複数",
        allergy_voice: "その他(声で入力)",
        med_title: "飲んでいる薬はありますか？", med_none: "飲んでいません", med_cold: "かぜ薬", med_pain: "痛み止め", med_digest: "胃腸薬", med_hospital: "病院の薬", med_idk: "わかりません", summary_med_info: "💊 服用中の薬", summary_med_label: "服用薬",
        arm_left_all: "左うで全体", arm_right_all: "右うで全体", arm_left_mid: "左ひじ・前うで", arm_right_mid: "右ひじ・前うで", arm_left_bot: "左手・手首", arm_right_bot: "右手・手首", arm_left_multi: "左うで複数", arm_right_multi: "右うで複数",
        allergy_voice: "その他(声で入力)",
        nurse_mode: "ほけんしつモード",
        pin_prompt: "パスワードをいれてください:",
        no_records: "きろくがありません。",
        delete: "けす",
        summary_title: "AIのまとめ",
        error_api: "まとめづくりにしっぱいしました。",
        summary_symptom: "しょうじょう",
        summary_part: "ばしょ",
        summary_symptom_label: "しょうじょう",
        summary_pain: "いたさ",
        summary_time: "いつから",
        summary_allergy_info: "🏥 アレルギーのじょうほう",
        summary_allergy_label: "アレルギー",
        pain_min: "いたくない",
        pain_max: "すごくいたい",
        btn_start_over: "さいしょからやりなおす",
        popup_success: "おくりました！",
        popup_desc: "せんせいに伝わりました。",
        belly_chest: "むね", profile_title: "じょうほうをいれる", profile_grade: "がくねん", profile_class: "くみ", profile_number: "ばんごう", profile_name: "なまえ", profile_placeholder: "ここにかいてね", profile_next: "つぎへ"
    },
    tl: {
    arm_left_upper: "Kaliwang Itaas na Braso",
    arm_left_elbow: "Kaliwang Siko",
    arm_left_lower: "Kaliwang Braso",
    arm_left_wrist: "Kaliwang Pulso",
    arm_left_hand: "Kaliwang Kamay",
    arm_right_upper: "Kanang Itaas na Braso",
    arm_right_elbow: "Kanang Siko",
    arm_right_lower: "Kanang Braso",
    arm_right_wrist: "Kanang Pulso",
    arm_right_hand: "Kanang Kamay",

    time_p1: "Ika-1 klase",
    time_p2: "Ika-2 klase",
    time_p3: "Ika-3 klase",
    time_p4: "Ika-4 klase",
    time_lunch: "Tanghalian",
    time_p5: "Ika-5 klase",
    time_p6: "Ika-6 klase",
    time_before: "Bago pumasok",
    time_days: "Ilang araw na",
    follow_trauma: "Paano ka nasugatan?",
    trauma_friend: "Naglalaro kasama ang kaibigan",
    trauma_alone: "Nahulog/nabangga mag-isa",
    trauma_sports: "Sa PE/Sports",

        belly_all: "Buong tiyan",
        belly_top_all: "Buong itaas",
        belly_bottom_all: "Buong ibaba",
        belly_left_top: "Kaliwang itaas",
        belly_right_top: "Kanang itaas",
        belly_left_bottom: "Kaliwang ibaba",
        belly_right_bottom: "Kanang ibaba",
        pain_1: "Sakit 1",
        pain_2: "Sakit 2",

        lang_name: "Tagalog",
        step_0_title: "Pumili ng wika",
        step_1_title: "Saan ang masakit?",
        step_2_title: "Paano sumasakit?",
        step_3_title: "Gaano kasakit?",
        step_4_title: "Kailan pa nagsimula?",
        step_5_title: "Tama ba ito?",
        btn_prev: "Bumalik",
        btn_next: "Susunod",
        btn_submit: "Oo (Ipadala)",
        btn_restart: "May masakit pa",
        quick_1: "Nasugatan ako",
        quick_2: "Masakit ang tiyan",
        quick_3: "Masakit ang ulo",
        quick_4: "May lagnat",
        quick_5: "Dumudugo ang ilong",
        quick_6: "Gusto kong sumuka",
        front: "Harap",
        back: "Likod",
        idk: "Hindi ko po alam",
        part_head: "Ulo",
        part_eye: "Mata",
        part_ear: "Tainga",
        part_nose: "Ilong",
        part_mouth: "Bibig/Ngipin",
        part_neck: "Leeg",
        part_chest: "Dibdib",
        part_belly: "Tiyan",
        part_arm: "Kamay/Braso",
        part_leg: "Binti/Paa",
        part_back: "Likod",
        part_skin: "Balat",
        part_whole: "Buong katawan",
        side_select_arm: "Aling braso?",
        side_select_leg: "Aling binti?",
        side_left: "Kaliwa",
        side_right: "Kanan",
        side_both: "Pariho",
        belly_top: "Itaas ng tiyan",
        belly_navel: "Paligid ng pusod",
        belly_bottom: "Ibaba ng tiyan",
        belly_right_bottom: "Kanang ibaba ng tiyan",
        arm_upper: "Balikat/Itaas na braso",
        arm_lower: "Siko/Ibabang braso",
        arm_hand: "Kamay/Pulso",
        leg_thigh: "Hita",
        leg_knee: "Tuhod",
        leg_calf: "Binti/Bukung-bukong",
        leg_foot: "Paa",
        hurt_how: "Paano ka nasugatan?",
        hurt_state: "Ano ang pakiramdam ngayon?",
        hurt_1: "Nadapa",
        hurt_2: "Nabangga",
        hurt_3: "Nahiwa",
        hurt_4: "Natapilok",
        state_1: "Dumudugo",
        state_2: "Namamaga",
        state_3: "May pasa",
        state_4: "Masakit kapag gumagalaw",
        head_q: "Nahihilo ka ba o parang gusto mong sumuka?",
        yes: "Opo",
        no: "Hindi po",        follow_belly: "Kumain ka na ba?",
        follow_fever: "Uminom ka na ba ng gamot?",
        follow_vomit: "Ilang beses kang sumuka?",
        vomit_1: "1 beses",
        vomit_2: "2 beses",
        vomit_3: "3 beses o higit pa",
        allergy_title: "May allergy ka ba?",
        allergy_none: "Wala po",
        allergy_drug: "Gamot",
        allergy_peanut: "Mani/Nuts",
        allergy_milk: "Gatas",
        allergy_egg: "Itlog",
        allergy_seafood: "Seafood",
        allergy_peach: "Peach",
        allergy_wheat: "Trigo",
        med_title: "Umiinom ka ba ng gamot?", med_none: "Wala", med_cold: "Gamot sa sipon", med_pain: "Pampasakit", med_digest: "Pampatunaw", med_hospital: "Reseta", med_idk: "Hindi ko alam", summary_med_info: "💊 Kasalukuyang Gamot", summary_med_label: "Gamot",
        arm_left_all: "Buong kaliwang braso", arm_right_all: "Buong kanang braso", arm_left_mid: "Kaliwang siko·braso", arm_right_mid: "Kanang siko·braso", arm_left_bot: "Kaliwang kamay·pulso", arm_right_bot: "Kanang kamay·pulso", arm_left_multi: "Kaliwang braso (marami)", arm_right_multi: "Kanang braso (marami)",
        allergy_voice: "Iba pa (magsalita)",
        med_title: "Umiinom ka ba ng gamot?", med_none: "Wala", med_cold: "Gamot sa sipon", med_pain: "Pampasakit", med_digest: "Pampatunaw", med_hospital: "Reseta", med_idk: "Hindi ko alam", summary_med_info: "💊 Kasalukuyang Gamot", summary_med_label: "Gamot",
        arm_left_all: "Buong kaliwang braso", arm_right_all: "Buong kanang braso", arm_left_mid: "Kaliwang siko·braso", arm_right_mid: "Kanang siko·braso", arm_left_bot: "Kaliwang kamay·pulso", arm_right_bot: "Kanang kamay·pulso", arm_left_multi: "Kaliwang braso (marami)", arm_right_multi: "Kanang braso (marami)",
        allergy_voice: "Iba pa (magsalita)",
        nurse_mode: "Nurse Mode",
        pin_prompt: "Ilagay ang PIN:",
        no_records: "Walang nakitang record.",
        delete: "Burahin",
        summary_title: "AI Summary",
        error_api: "May error sa paggawa ng summary.",
        summary_symptom: "Sintomas",
        summary_part: "Bahagi",
        summary_symptom_label: "Sintomas",
        summary_pain: "Gaano Kasakit",
        summary_time: "Oras Nagsimula",
        summary_allergy_info: "🏥 Impormasyon sa Allergy",
        summary_allergy_label: "Mga Allergy",
        pain_min: "Hindi masakit",
        pain_max: "Sobra ang sakit",
        btn_start_over: "Ulitin",
        popup_success: "Naipadala Na!",
        popup_desc: "Naipadala na ito sa teacher.",
        belly_chest: "Dibdib", profile_title: "Impormasyon", profile_grade: "Baitang", profile_class: "Seksyon", profile_number: "Numero", profile_name: "Pangalan", profile_placeholder: "Ilagay", profile_next: "Susunod"
    },
    km: {
    arm_left_upper: "ដើមដៃឆ្វេង",
    arm_left_elbow: "កែងដៃឆ្វេង",
    arm_left_lower: "កំភួនដៃឆ្វេង",
    arm_left_wrist: "កដៃឆ្វេង",
    arm_left_hand: "ដៃឆ្វេង",
    arm_right_upper: "ដើមដៃស្តាំ",
    arm_right_elbow: "កែងដៃស្តាំ",
    arm_right_lower: "កំភួនដៃស្តាំ",
    arm_right_wrist: "កដៃស្តាំ",
    arm_right_hand: "ដៃស្តាំ",

    time_p1: "ម៉ោងទី 1",
    time_p2: "ម៉ោងទី 2",
    time_p3: "ម៉ោងទី 3",
    time_p4: "ម៉ោងទី 4",
    time_lunch: "ម៉ោងញ៉ាំបាយ",
    time_p5: "ម៉ោងទី 5",
    time_p6: "ម៉ោងទី 6",
    time_before: "មុនមកសាលា",
    time_days: "ពីរបីថ្ងៃមុន",
    follow_trauma: "តើអ្នករបួសយ៉ាងដូចម្តេច?",
    trauma_friend: "លេងជាមួយមិត្តភក្តិ",
    trauma_alone: "ដួល/ប៉ះពាល់តែឯង",
    trauma_sports: "ពេលរៀនកីឡា",

        belly_all: "ពោះទាំងមូល",
        belly_top_all: "ពោះផ្នែកខាងលើទាំងមូល",
        belly_bottom_all: "ពោះផ្នែកខាងក្រោមទាំងមូល",
        belly_left_top: "ពោះខាងឆ្វេងផ្នែកខាងលើ",
        belly_right_top: "ពោះខាងស្តាំផ្នែកខាងលើ",
        belly_left_bottom: "ពោះខាងឆ្វេងផ្នែកខាងក្រោម",
        belly_right_bottom: "ពោះខាងស្តាំផ្នែកខាងក្រោម",
        pain_1: "ការឈឺចាប់ទី 1",
        pain_2: "ការឈឺចាប់ទី 2",

        lang_name: "ភាសាខ្មែរ",
        step_0_title: "ជ្រើសរើសភាសារបស់អ្នក។",
        step_1_title: "តើអ្នកឈឺនៅឯណា?",
        step_2_title: "តើអ្នកឈឺយ៉ាងម៉េច?",
        step_3_title: "តើអ្នកឈឺប៉ុណ្ណា?",
        step_4_title: "តើអ្នកឈឺតាំងពីពេលណា?",
        step_5_title: "ផ្ញើបែបនេះមែនទេ?",
        btn_prev: "ថយក្រោយ",
        btn_next: "បន្ទាប់",
        btn_submit: "បញ្ជូន",
        btn_restart: "ខ្ញុំឈឺកន្លែងផ្សេងទៀត",
        quick_1: "ខ្ញុំមានរបួស",
        quick_2: "ខ្ញុំឈឺពោះ",
        quick_3: "ខ្ញុំឈឺក្បាល",
        quick_4: "ខ្ញុំក្តៅខ្លួន",
        quick_5: "ខ្ញុំហូរឈាមច្រមុះ",
        quick_6: "ខ្ញុំចង់ក្អួត",
        front: "ខាងមុខ",
        back: "ខាងក្រោយ",
        idk: "ខ្ញុំមិនដឹងទេ",
        part_head: "ក្បាល",
        part_eye: "ភ្នែក",
        part_ear: "ត្រចៀក",
        part_nose: "ច្រមុះ",
        part_mouth: "មាត់/ធ្មេញ",
        part_neck: "ក",
        part_chest: "ទ្រូង",
        part_belly: "ពោះ",
        part_arm: "ដៃ",
        part_leg: "ជើង",
        part_back: "ខ្នង",
        part_skin: "ស្បែក",
        part_whole: "ពេញរាងកាយ",
        side_select_arm: "ដៃមួយណា?",
        side_select_leg: "ជើងមួយណា?",
        side_left: "ខាងឆ្វេង",
        side_right: "ខាងស្តាំ",
        side_both: "ទាំងពីរ",
        belly_top: "ពោះផ្នែកខាងលើ",
        belly_navel: "ជុំវិញផ្ចិត",
        belly_bottom: "ពោះផ្នែកខាងក្រោម",
        belly_right_bottom: "ផ្នែកខាងក្រោមខាងស្តាំ",
        arm_upper: "ស្មា/ដើមដៃ",
        arm_lower: "កែងដៃ/កំភួនដៃ",
        arm_hand: "បាតដៃ/កដៃ",
        leg_thigh: "ភ្លៅ",
        leg_knee: "ជង្គង់",
        leg_calf: "កំភួនជើង/កជើង",
        leg_foot: "ប្រអប់ជើង",
        hurt_how: "តើអ្នករងរបួសដោយរបៀបណា?",
        hurt_state: "តើឥឡូវនេះយ៉ាងម៉េចហើយ?",
        hurt_1: "ខ្ញុំដួល",
        hurt_2: "ខ្ញុំបុក",
        hurt_3: "ខ្ញុំមុត",
        hurt_4: "ខ្ញុំគ្រេច",
        state_1: "ខ្ញុំហូរឈាម",
        state_2: "ខ្ញុំហើម",
        state_3: "ខ្ញុំជាំ",
        state_4: "វាឈឺនៅពេលខ្ញុំកម្រើក",
        head_q: "តើអ្នកវិលមុខឬចង់ក្អួតទេ?",
        yes: "បាទ/ចាស",
        no: "ទេ",        follow_belly: "តើអ្នកបានញ៉ាំបាយទេ?",
        follow_fever: "តើអ្នកបានលេបថ្នាំទេ?",
        follow_vomit: "តើអ្នកបានក្អួតប៉ុន្មានដង?",
        vomit_1: "១ ដង",
        vomit_2: "២ ដង",
        vomit_3: "៣ ដងឬច្រើនជាងនេះ",
        allergy_title: "តើអ្នកមានអាឡែស៊ីទេ?",
        allergy_none: "គ្មានទេ",
        allergy_drug: "ថ្នាំពេទ្យ",
        allergy_peanut: "សណ្តែកដី/គ្រាប់ធញ្ញជាតិ",
        allergy_milk: "ទឹកដោះគោ",
        allergy_egg: "ស៊ុត",
        allergy_seafood: "អាហារសមុទ្រ",
        allergy_peach: "ផ្លែប៉េស",
        allergy_wheat: "ស្រូវសាលី",
        med_title: "តើអ្នកកំពុងលេបថ្នាំអ្វីខ្លះ?", med_none: "គ្មានទេ", med_cold: "ថ្នាំផ្តាសាយ", med_pain: "ថ្នាំបំបាត់ការឈឺចាប់", med_digest: "ថ្នាំរំលាយអាហារ", med_hospital: "ថ្នាំវេជ្ជបញ្ជា", med_idk: "ខ្ញុំមិនដឹងទេ", summary_med_info: "💊 ថ្នាំកំពុងលេប", summary_med_label: "ថ្នាំ",
        arm_left_all: "ដៃឆ្វេងទាំងមូល", arm_right_all: "ដៃស្តាំទាំងមូល", arm_left_mid: "កែងដៃឆ្វេង·សាច់ដៃ", arm_right_mid: "កែងដៃស្តាំ·សាច់ដៃ", arm_left_bot: "ដៃឆ្វេង·កដៃ", arm_right_bot: "ដៃស្តាំ·កដៃ", arm_left_multi: "ដៃឆ្វេង(ច្រើន)", arm_right_multi: "ដៃស្តាំ(ច្រើន)",
        allergy_voice: "ផ្សេងៗ(និយាយ)",
        med_title: "តើអ្នកកំពុងលេបថ្នាំអ្វីខ្លះ?", med_none: "គ្មានទេ", med_cold: "ថ្នាំផ្តាសាយ", med_pain: "ថ្នាំបំបាត់ការឈឺចាប់", med_digest: "ថ្នាំរំលាយអាហារ", med_hospital: "ថ្នាំវេជ្ជបញ្ជា", med_idk: "ខ្ញុំមិនដឹងទេ", summary_med_info: "💊 ថ្នាំកំពុងលេប", summary_med_label: "ថ្នាំ",
        arm_left_all: "ដៃឆ្វេងទាំងមូល", arm_right_all: "ដៃស្តាំទាំងមូល", arm_left_mid: "កែងដៃឆ្វេង·សាច់ដៃ", arm_right_mid: "កែងដៃស្តាំ·សាច់ដៃ", arm_left_bot: "ដៃឆ្វេង·កដៃ", arm_right_bot: "ដៃស្តាំ·កដៃ", arm_left_multi: "ដៃឆ្វេង(ច្រើន)", arm_right_multi: "ដៃស្តាំ(ច្រើន)",
        allergy_voice: "ផ្សេងៗ(និយាយ)",
        nurse_mode: "របៀបគិលានុបដ្ឋាយិកា",
        pin_prompt: "បញ្ចូលលេខសម្ងាត់៖",
        no_records: "គ្មានកំណត់ត្រាទេ។",
        delete: "លុប",
        summary_title: "សេចក្តីសង្ខេប AI",
        error_api: "មានកំហុសក្នុងការបង្កើតសេចក្តីសង្ខេប។",
        summary_symptom: "រោគសញ្ញា",
        summary_part: "ផ្នែក",
        summary_symptom_label: "រោគសញ្ញា",
        summary_pain: "កម្រិតនៃការឈឺចាប់",
        summary_time: "ពេលវេលាចាប់ផ្តើម",
        summary_allergy_info: "🏥 ព័ត៌មានអំពីអាឡែស៊ី",
        summary_allergy_label: "អាឡែស៊ី",
        pain_min: "មិនឈឺទេ",
        pain_max: "ឈឺខ្លាំងណាស់",
        btn_start_over: "ចាប់ផ្តើមម្តងទៀត",
        popup_success: "បានផ្ញើដោយជោគជ័យ!",
        popup_desc: "វាត្រូវបានផ្ញើទៅលោកគ្រូអ្នកគ្រូ។",
        belly_chest: "ទ្រូង", profile_title: "បញ្ចូលព័ត៌មាន", profile_grade: "ថ្នាក់", profile_class: "បន្ទប់", profile_number: "លេខ", profile_name: "ឈ្មោះ", profile_placeholder: "សរសេរ", profile_next: "បន្ទាប់"
    },
    th: {
    arm_left_upper: "ต้นแขนซ้าย",
    arm_left_elbow: "ข้อศอกซ้าย",
    arm_left_lower: "ปลายแขนซ้าย",
    arm_left_wrist: "ข้อมือซ้าย",
    arm_left_hand: "มือซ้าย",
    arm_right_upper: "ต้นแขนขวา",
    arm_right_elbow: "ข้อศอกขวา",
    arm_right_lower: "ปลายแขนขวา",
    arm_right_wrist: "ข้อมือขวา",
    arm_right_hand: "มือขวา",

    time_p1: "คาบ 1",
    time_p2: "คาบ 2",
    time_p3: "คาบ 3",
    time_p4: "คาบ 4",
    time_lunch: "พักกลางวัน",
    time_p5: "คาบ 5",
    time_p6: "คาบ 6",
    time_before: "ก่อนมาโรงเรียน",
    time_days: "หลายวันก่อน",
    follow_trauma: "เจ็บได้ยังไง?",
    trauma_friend: "เล่นกับเพื่อน",
    trauma_alone: "ล้ม/ชนเอง",
    trauma_sports: "ตอนเรียนพละ/เล่นกีฬา",

        belly_all: "ท้องทั้งหมด",
        belly_top_all: "ท้องส่วนบนทั้งหมด",
        belly_bottom_all: "ท้องส่วนล่างทั้งหมด",
        belly_left_top: "ท้องส่วนบนซ้าย",
        belly_right_top: "ท้องส่วนบนขวา",
        belly_left_bottom: "ท้องส่วนล่างซ้าย",
        belly_right_bottom: "ท้องส่วนล่างขวา",
        pain_1: "ความเจ็บปวด 1",
        pain_2: "ความเจ็บปวด 2",

        lang_name: "ภาษาไทย",
        step_0_title: "เลือกภาษาของคุณ",
        step_1_title: "เจ็บตรงไหนคะ/ครับ?",
        step_2_title: "เจ็บแบบไหนคะ/ครับ?",
        step_3_title: "เจ็บมากไหมคะ/ครับ?",
        step_4_title: "เริ่มเป็นตั้งแต่เมื่อไหร่คะ/ครับ?",
        step_5_title: "ส่งแบบนี้เลยไหมคะ/ครับ?",
        btn_prev: "ย้อนกลับ",
        btn_next: "ถัดไป",
        btn_submit: "ส่ง",
        btn_restart: "หนู/ผมเจ็บที่อื่นด้วย",
        quick_1: "หนู/ผมบาดเจ็บ",
        quick_2: "หนู/ผมปวดท้อง",
        quick_3: "หนู/ผมปวดหัว",
        quick_4: "หนู/ผมมีไข้",
        quick_5: "หนู/ผมเลือดกำเดาไหล",
        quick_6: "หนู/ผมอยากอ้วก",
        front: "ด้านหน้า",
        back: "ด้านหลัง",
        idk: "หนู/ผมไม่รู้",
        part_head: "หัว",
        part_eye: "ตา",
        part_ear: "หู",
        part_nose: "จมูก",
        part_mouth: "ปาก/ฟัน",
        part_neck: "คอ",
        part_chest: "หน้าอก",
        part_belly: "ท้อง",
        part_arm: "แขน/มือ",
        part_leg: "ขา/เท้า",
        part_back: "หลัง",
        part_skin: "ผิวหนัง",
        part_whole: "ทั้งตัว",
        side_select_arm: "แขนข้างไหนคะ/ครับ?",
        side_select_leg: "ขาข้างไหนคะ/ครับ?",
        side_left: "ข้างซ้าย",
        side_right: "ข้างขวา",
        side_both: "ทั้งสองข้าง",
        belly_top: "ท้องส่วนบน",
        belly_navel: "รอบสะดือ",
        belly_bottom: "ท้องส่วนล่าง",
        belly_right_bottom: "ท้องด้านล่างขวา",
        arm_upper: "ไหล่/ต้นแขน",
        arm_lower: "ข้อศอก/แขนท่อนล่าง",
        arm_hand: "มือ/ข้อมือ",
        leg_thigh: "ต้นขา",
        leg_knee: "หัวเข่า",
        leg_calf: "น่อง/ข้อเท้า",
        leg_foot: "เท้า",
        hurt_how: "หนู/ผมไปโดนอะไรมาคะ/ครับ?",
        hurt_state: "ตอนนี้เป็นยังไงบ้างคะ/ครับ?",
        hurt_1: "หนู/ผมล้ม",
        hurt_2: "หนู/ผมชน",
        hurt_3: "หนู/ผมโดนบาด",
        hurt_4: "หนู/ผมข้อเท้าพลิก",
        state_1: "เลือดไหล",
        state_2: "มันบวม",
        state_3: "มันฟกช้ำ",
        state_4: "ขยับแล้วเจ็บ",
        head_q: "หนู/ผมรู้สึกเวียนหัวหรืออยากอ้วกไหมคะ/ครับ?",
        yes: "ใช่คะ/ครับ",
        no: "ไม่คะ/ครับ",        follow_belly: "หนู/ผมกินข้าวหรือยังคะ/ครับ?",
        follow_fever: "หนู/ผมกินยาหรือยังคะ/ครับ?",
        follow_vomit: "หนู/ผมอ้วกกี่ครั้งคะ/ครับ?",
        vomit_1: "1 ครั้ง",
        vomit_2: "2 ครั้ง",
        vomit_3: "3 ครั้งขึ้นไป",
        allergy_title: "หนู/ผมแพ้อะไรไหมคะ/ครับ?",
        allergy_none: "ไม่แพ้อะไรเลย",
        allergy_drug: "ยา",
        allergy_peanut: "ถั่วลิสง/ถั่ว",
        allergy_milk: "นม",
        allergy_egg: "ไข่",
        allergy_seafood: "อาหารทะเล",
        allergy_peach: "ลูกพีช",
        allergy_wheat: "ข้าวสาลี",
        med_title: "กินยาอะไรอยู่ไหม?", med_none: "ไม่ได้กิน", med_cold: "ยาแก้หวัด", med_pain: "ยาแก้ปวด", med_digest: "ยาธาตุ", med_hospital: "ยาจากโรงพยาบาล", med_idk: "ไม่รู้", summary_med_info: "💊 ยาที่กินอยู่", summary_med_label: "ยา",
        arm_left_all: "แขนซ้ายทั้งหมด", arm_right_all: "แขนขวาทั้งหมด", arm_left_mid: "ศอกซ้าย·แขน", arm_right_mid: "ศอกขวา·แขน", arm_left_bot: "มือซ้าย·ข้อมือ", arm_right_bot: "มือขวา·ข้อมือ", arm_left_multi: "แขนซ้าย(หลายจุด)", arm_right_multi: "แขนขวา(หลายจุด)",
        allergy_voice: "อื่นๆ(พูด)",
        med_title: "กินยาอะไรอยู่ไหม?", med_none: "ไม่ได้กิน", med_cold: "ยาแก้หวัด", med_pain: "ยาแก้ปวด", med_digest: "ยาธาตุ", med_hospital: "ยาจากโรงพยาบาล", med_idk: "ไม่รู้", summary_med_info: "💊 ยาที่กินอยู่", summary_med_label: "ยา",
        arm_left_all: "แขนซ้ายทั้งหมด", arm_right_all: "แขนขวาทั้งหมด", arm_left_mid: "ศอกซ้าย·แขน", arm_right_mid: "ศอกขวา·แขน", arm_left_bot: "มือซ้าย·ข้อมือ", arm_right_bot: "มือขวา·ข้อมือ", arm_left_multi: "แขนซ้าย(หลายจุด)", arm_right_multi: "แขนขวา(หลายจุด)",
        allergy_voice: "อื่นๆ(พูด)",
        nurse_mode: "โหมดคุณครูพยาบาล",
        pin_prompt: "ใส่รหัสผ่าน:",
        no_records: "ไม่พบข้อมูล",
        delete: "ลบ",
        summary_title: "สรุปโดย AI",
        error_api: "เกิดข้อผิดพลาดในการสรุป",
        summary_symptom: "อาการ",
        summary_part: "ส่วนที่เจ็บ",
        summary_symptom_label: "อาการต่างๆ",
        summary_pain: "ระดับความเจ็บ",
        summary_time: "เวลาที่เริ่มเจ็บ",
        summary_allergy_info: "🏥 ข้อมูลการแพ้",
        summary_allergy_label: "สิ่งที่แพ้",
        pain_min: "ไม่เจ็บเลย",
        pain_max: "เจ็บมากๆ",
        btn_start_over: "เริ่มใหม่",
        popup_success: "ส่งสำเร็จแล้ว!",
        popup_desc: "ส่งให้คุณครูเรียบร้อยแล้ว",
        belly_chest: "หน้าอก", profile_title: "ใส่ข้อมูล", profile_grade: "ชั้น", profile_class: "ห้อง", profile_number: "เลขที่", profile_name: "ชื่อ", profile_placeholder: "พิมพ์", profile_next: "ถัดไป"
    },
    mn: {
    arm_left_upper: "Зүүн бугалга",
    arm_left_elbow: "Зүүн тохой",
    arm_left_lower: "Зүүн шуу",
    arm_left_wrist: "Зүүн бугуй",
    arm_left_hand: "Зүүн гар",
    arm_right_upper: "Баруун бугалга",
    arm_right_elbow: "Баруун тохой",
    arm_right_lower: "Баруун шуу",
    arm_right_wrist: "Баруун бугуй",
    arm_right_hand: "Баруун гар",

    time_p1: "1-р цаг",
    time_p2: "2-р цаг",
    time_p3: "3-р цаг",
    time_p4: "4-р цаг",
    time_lunch: "Үдийн цай",
    time_p5: "5-р цаг",
    time_p6: "6-р цаг",
    time_before: "Сургуульд ирэхээс өмнө",
    time_days: "Хэдэн өдрийн өмнө",
    follow_trauma: "Яаж гэмтсэн бэ?",
    trauma_friend: "Найзтайгаа тоглож байгаад",
    trauma_alone: "Ганцаараа унасан/мөргөсөн",
    trauma_sports: "Биеийн тамирын цагаар",

        belly_all: "Бүхэл бүтэн гэдэс",
        belly_top_all: "Гэдэсний дээд хэсэг",
        belly_bottom_all: "Гэдэсний доод хэсэг",
        belly_left_top: "Зүүн дээд хэсэг",
        belly_right_top: "Баруун дээд хэсэг",
        belly_left_bottom: "Зүүн доод хэсэг",
        belly_right_bottom: "Баруун доод хэсэг",
        pain_1: "Өвдөлт 1",
        pain_2: "Өвдөлт 2",

        lang_name: "Монгол хэл",
        step_0_title: "Хэлээ сонгоно уу.",
        step_1_title: "Хаана өвдөж байна вэ?",
        step_2_title: "Яаж өвдөж байна вэ?",
        step_3_title: "Хэр их өвдөж байна вэ?",
        step_4_title: "Хэзээнээс өвдөж эхэлсэн бэ?",
        step_5_title: "Ингээд илгээх үү?",
        btn_prev: "Буцах",
        btn_next: "Дараах",
        btn_submit: "Илгээх",
        btn_restart: "Өөр газар бас өвдөж байна",
        quick_1: "Би бэртчихлээ",
        quick_2: "Миний гэдэс өвдөж байна",
        quick_3: "Миний толгой өвдөж байна",
        quick_4: "Би халуурч байна",
        quick_5: "Миний хамарнаас цус гарч байна",
        quick_6: "Би бөөлжмөөр байна",
        front: "Урд тал",
        back: "Ар тал",
        idk: "Би мэдэхгүй байна",
        part_head: "Толгой",
        part_eye: "Нүд",
        part_ear: "Чих",
        part_nose: "Хамар",
        part_mouth: "Ам/Шүд",
        part_neck: "Хүзүү",
        part_chest: "Цээж",
        part_belly: "Гэдэс",
        part_arm: "Гар/Бугуй",
        part_leg: "Хөл",
        part_back: "Нуруу",
        part_skin: "Арьс",
        part_whole: "Бүх бие",
        side_select_arm: "Аль гар вэ?",
        side_select_leg: "Аль хөл вэ?",
        side_left: "Зүүн тал",
        side_right: "Баруун тал",
        side_both: "Хоёр тал хоёулаа",
        belly_top: "Гэдэсний дээд хэсэг",
        belly_navel: "Хүйсний эргэн тойронд",
        belly_bottom: "Гэдэсний доод хэсэг",
        belly_right_bottom: "Гэдэсний баруун доод хэсэг",
        arm_upper: "Мөр/Бугалга",
        arm_lower: "Тохой/Шуу",
        arm_hand: "Гар/Бугуй",
        leg_thigh: "Гуя",
        leg_knee: "Өвдөг",
        leg_calf: "Шилбэ/Шагай",
        leg_foot: "Тавхай",
        hurt_how: "Чи яаж бэртсэн бэ?",
        hurt_state: "Одоо ямар байна вэ?",
        hurt_1: "Би уначихсан",
        hurt_2: "Би мөргөчихсөн",
        hurt_3: "Би зүсчихсэн",
        hurt_4: "Би булгалчихсан",
        state_1: "Цус гарч байна",
        state_2: "Хавдсан байна",
        state_3: "Хөхөрсөн байна",
        state_4: "Хөдлөхөөр өвдөж байна",
        head_q: "Толгой эргэж эсвэл бөөлжмөөр байна уу?",
        yes: "Тийм",
        no: "Үгүй",        follow_belly: "Чи хоол идсэн үү?",
        follow_fever: "Чи эм уусан уу?",
        follow_vomit: "Чи хэдэн удаа бөөлжсөн бэ?",
        vomit_1: "1 удаа",
        vomit_2: "2 удаа",
        vomit_3: "3 ба түүнээс дээш удаа",
        allergy_title: "Чамд харшил байдаг уу?",
        allergy_none: "Байхгүй",
        allergy_drug: "Эм",
        allergy_peanut: "Самар",
        allergy_milk: "Сүү",
        allergy_egg: "Өндөг",
        allergy_seafood: "Далайн гаралтай хоол",
        allergy_peach: "Тоор",
        allergy_wheat: "Улаан буудай",
        med_title: "Ямар нэгэн эм уудаг уу?", med_none: "Үгүй", med_cold: "Ханиадны эм", med_pain: "Өвдөлт намдаах эм", med_digest: "Хоол боловсруулах эм", med_hospital: "Эмчийн жор", med_idk: "Мэдэхгүй байна", summary_med_info: "💊 Уудаг эм", summary_med_label: "Эм",
        arm_left_all: "Зүүн гар бүхэлд нь", arm_right_all: "Баруун гар бүхэлд нь", arm_left_mid: "Зүүн тохой·бугалга", arm_right_mid: "Баруун тохой·бугалга", arm_left_bot: "Зүүн гар·бугуй", arm_right_bot: "Баруун гар·бугуй", arm_left_multi: "Зүүн гар (олон)", arm_right_multi: "Баруун гар (олон)",
        allergy_voice: "Бусад (ярих)",
        med_title: "Ямар нэгэн эм уудаг уу?", med_none: "Үгүй", med_cold: "Ханиадны эм", med_pain: "Өвдөлт намдаах эм", med_digest: "Хоол боловсруулах эм", med_hospital: "Эмчийн жор", med_idk: "Мэдэхгүй байна", summary_med_info: "💊 Уудаг эм", summary_med_label: "Эм",
        arm_left_all: "Зүүн гар бүхэлд нь", arm_right_all: "Баруун гар бүхэлд нь", arm_left_mid: "Зүүн тохой·бугалга", arm_right_mid: "Баруун тохой·бугалга", arm_left_bot: "Зүүн гар·бугуй", arm_right_bot: "Баруун гар·бугуй", arm_left_multi: "Зүүн гар (олон)", arm_right_multi: "Баруун гар (олон)",
        allergy_voice: "Бусад (ярих)",
        nurse_mode: "Сувилагчийн горим",
        pin_prompt: "Нууц үгээ оруулна уу:",
        no_records: "Бүртгэл олдсонгүй.",
        delete: "Устгах",
        summary_title: "AI Дүгнэлт",
        error_api: "Дүгнэлт гаргахад алдаа гарлаа.",
        summary_symptom: "Шинж тэмдэг",
        summary_part: "Биеийн хэсэг",
        summary_symptom_label: "Шинж тэмдгүүд",
        summary_pain: "Өвдөлтийн түвшин",
        summary_time: "Эхэлсэн цаг",
        summary_allergy_info: "🏥 Харшлын мэдээлэл",
        summary_allergy_label: "Харшил",
        pain_min: "Өвдөхгүй байна",
        pain_max: "Маш их өвдөж байна",
        btn_start_over: "Дахин эхлэх",
        popup_success: "Амжилттай илгээгдлээ!",
        popup_desc: "Багшид илгээгдлээ.",
        belly_chest: "Цээж", profile_title: "Мэдээлэл оруулах", profile_grade: "Анги", profile_class: "Бүлэг", profile_number: "Дугаар", profile_name: "Нэр", profile_placeholder: "Бичих", profile_next: "Дараах"
    },
    uz: {
    arm_left_upper: "Chap yuqori qo`l",
    arm_left_elbow: "Chap tirsak",
    arm_left_lower: "Chap bilak",
    arm_left_wrist: "Chap bilak(qo`l)",
    arm_left_hand: "Chap qo`l",
    arm_right_upper: "O`ng yuqori qo`l",
    arm_right_elbow: "O`ng tirsak",
    arm_right_lower: "O`ng bilak",
    arm_right_wrist: "O`ng bilak(qo`l)",
    arm_right_hand: "O`ng qo`l",

    time_p1: "1-dars",
    time_p2: "2-dars",
    time_p3: "3-dars",
    time_p4: "4-dars",
    time_lunch: "Tushlik",
    time_p5: "5-dars",
    time_p6: "6-dars",
    time_before: "Maktabgacha",
    time_days: "Bir necha kun oldin",
    follow_trauma: "Qanday jarohat oldingiz?",
    trauma_friend: "Dost bilan oynab",
    trauma_alone: "Ozi yiqildi/urib oldi",
    trauma_sports: "Jismoniy tarbiya darsida",

        belly_all: "Butun qorin",
        belly_top_all: "Butun yuqori qorin",
        belly_bottom_all: "Butun pastki qorin",
        belly_left_top: "Chap yuqori qorin",
        belly_right_top: "O'ng yuqori qorin",
        belly_left_bottom: "Chap pastki qorin",
        belly_right_bottom: "O'ng pastki qorin",
        pain_1: "Og'riq 1",
        pain_2: "Og'riq 2",

        lang_name: "O'zbek",
        step_0_title: "Tilingizni tanlang.",
        step_1_title: "Qayeringiz og'riyapti?",
        step_2_title: "Qanday og'riyapti?",
        step_3_title: "Qanchalik og'riyapti?",
        step_4_title: "Qachon boshlandi?",
        step_5_title: "Shu to'g'rimi?",
        btn_prev: "Orqaga",
        btn_next: "Oldinga",
        btn_submit: "Yuborish",
        btn_restart: "Boshqa joyim ham og'riyapti",
        quick_1: "Jarohat oldim",
        quick_2: "Qornim og'riyapti",
        quick_3: "Boshim og'riyapti",
        quick_4: "Isitma",
        quick_5: "Burnimdan qon kelyapti",
        quick_6: "Ko'nglim ayniyapti",
        front: "Oldi",
        back: "Orqa",
        idk: "Bilmayman",
        part_head: "Bosh",
        part_eye: "Ko'z",
        part_ear: "Quloq",
        part_nose: "Burun",
        part_mouth: "Og'iz / Tish",
        part_neck: "Bo'yin",
        part_chest: "Ko'krak",
        part_belly: "Qorin",
        part_arm: "Qo'l",
        part_leg: "Oyoq",
        part_back: "Bel / Orqa",
        part_skin: "Teri",
        part_whole: "Butun tana",
        side_select_arm: "Qaysi qo'lingiz?",
        side_select_leg: "Qaysi oyog'ingiz?",
        side_left: "Chap",
        side_right: "O'ng",
        side_both: "Ikkisi ham",
        belly_top: "Tepa qorin",
        belly_navel: "Kindik atrofida",
        belly_bottom: "Pastki qorin",
        belly_right_bottom: "O'ng pastki qorin",
        arm_upper: "Yelka",
        arm_lower: "Tirsak",
        arm_hand: "Qo'l / Bilak",
        leg_thigh: "Son",
        leg_knee: "Tizza",
        leg_calf: "Boldir / To'piq",
        leg_foot: "Oyoq uchi",
        hurt_how: "Qanday jarohat oldingiz?",
        hurt_state: "Hozir qanday?",
        hurt_1: "Yiqilib tushdim",
        hurt_2: "Urib oldim",
        hurt_3: "Kesib oldim",
        hurt_4: "Qayirib oldim",
        state_1: "Qon kelyapti",
        state_2: "Ishib ketdi",
        state_3: "Ko'kardi",
        state_4: "Qimirlatsam og'riyapti",
        head_q: "Bosh aylanishi yoki ko'ngil aynishi bormi?",
        yes: "Ha",
        no: "Yo'q",        follow_belly: "Ovqat yedingizmi?",
        follow_fever: "Dori ichdingizmi?",
        follow_vomit: "Necha marta qayt qildingiz?",
        vomit_1: "1 marta",
        vomit_2: "2 marta",
        vomit_3: "3 yoki undan ko'p marta",
        allergy_title: "Allergiyangiz bormi?",
        allergy_none: "Yo'q",
        allergy_drug: "Dori",
        allergy_peanut: "Yeryong'oq / Yong'oq",
        allergy_milk: "Sut",
        allergy_egg: "Tuxum",
        allergy_seafood: "Dengiz mahsulotlari",
        allergy_peach: "Shaftoli",
        allergy_wheat: "Bug'doy",
        med_title: "Biror dori ichyapsizmi?", med_none: "Yo'q", med_cold: "Shamollash dorisi", med_pain: "Og'riq qoldiruvchi", med_digest: "Hazm qilish dorisi", med_hospital: "Retsept dorisi", med_idk: "Bilmayman", summary_med_info: "💊 Ichilayotgan dori", summary_med_label: "Dori",
        arm_left_all: "Chap qo'l butun", arm_right_all: "O'ng qo'l butun", arm_left_mid: "Chap tirsak·bilak", arm_right_mid: "O'ng tirsak·bilak", arm_left_bot: "Chap qo'l·bilak", arm_right_bot: "O'ng qo'l·bilak", arm_left_multi: "Chap qo'l (ko'p)", arm_right_multi: "O'ng qo'l (ko'p)",
        allergy_voice: "Boshqa (gapirib ayting)",
        med_title: "Biror dori ichyapsizmi?", med_none: "Yo'q", med_cold: "Shamollash dorisi", med_pain: "Og'riq qoldiruvchi", med_digest: "Hazm qilish dorisi", med_hospital: "Retsept dorisi", med_idk: "Bilmayman", summary_med_info: "💊 Ichilayotgan dori", summary_med_label: "Dori",
        arm_left_all: "Chap qo'l butun", arm_right_all: "O'ng qo'l butun", arm_left_mid: "Chap tirsak·bilak", arm_right_mid: "O'ng tirsak·bilak", arm_left_bot: "Chap qo'l·bilak", arm_right_bot: "O'ng qo'l·bilak", arm_left_multi: "Chap qo'l (ko'p)", arm_right_multi: "O'ng qo'l (ko'p)",
        allergy_voice: "Boshqa (gapirib ayting)",
        nurse_mode: "Hamshira rejimi",
        pin_prompt: "Parolni kiriting:",
        no_records: "Yozuvlar topilmadi.",
        delete: "O'chirish",
        summary_title: "AI Xulosasi",
        error_api: "Xulosa yaratishda xato.",
        summary_symptom: "Alomat",
        summary_part: "Qism",
        summary_symptom_label: "Alomatlar",
        summary_pain: "Og'riq darajasi",
        summary_time: "Boshlanish vaqti",
        summary_allergy_info: "🏥 Allergiya ma'lumoti",
        summary_allergy_label: "Allergiyalar",
        pain_min: "Og'rimayapti",
        pain_max: "Juda kuchli og'riyapti",
        btn_start_over: "Boshidan boshlash",
        popup_success: "Muvaffaqiyatli yuborildi!",
        popup_desc: "O'qituvchiga yuborildi.",
        belly_chest: "Ko'krak", profile_title: "Ma'lumot kiriting", profile_grade: "Sinf", profile_class: "Guruh", profile_number: "Raqam", profile_name: "Ism", profile_placeholder: "Yozing", profile_next: "Keyingi"
    },
    ar: {
    arm_left_upper: "الذراع العلوية اليسرى",
    arm_left_elbow: "الكوع الأيسر",
    arm_left_lower: "الساعد الأيسر",
    arm_left_wrist: "المعصم الأيسر",
    arm_left_hand: "اليد اليسرى",
    arm_right_upper: "الذراع العلوية اليمنى",
    arm_right_elbow: "الكوع الأيمن",
    arm_right_lower: "الساعد الأيمن",
    arm_right_wrist: "المعصم الأيمن",
    arm_right_hand: "اليد اليمنى",

    time_p1: "الحصة الأولى",
    time_p2: "الحصة الثانية",
    time_p3: "الحصة الثالثة",
    time_p4: "الحصة الرابعة",
    time_lunch: "وقت الغداء",
    time_p5: "الحصة الخامسة",
    time_p6: "الحصة السادسة",
    time_before: "قبل المدرسة",
    time_days: "منذ بضعة أيام",
    follow_trauma: "كيف أصبت؟",
    trauma_friend: "ألعب مع صديق",
    trauma_alone: "سقطت/اصطدمت وحدي",
    trauma_sports: "أثناء الرياضة",

        belly_all: "البطن بالكامل",
        belly_top_all: "أعلى البطن بالكامل",
        belly_bottom_all: "أسفل البطن بالكامل",
        belly_left_top: "أعلى يسار البطن",
        belly_right_top: "أعلى يمين البطن",
        belly_left_bottom: "أسفل يسار البطن",
        belly_right_bottom: "أسفل يمين البطن",
        pain_1: "ألم 1",
        pain_2: "ألم 2",

        lang_name: "العربية",
        step_0_title: "اختر لغتك.",
        step_1_title: "أين يؤلمك؟",
        step_2_title: "كيف يؤلمك؟",
        step_3_title: "كم يؤلمك؟",
        step_4_title: "متى بدأ؟",
        step_5_title: "هل هذا صحيح؟",
        btn_prev: "السابق",
        btn_next: "التالي",
        btn_submit: "إرسال",
        btn_restart: "مكان ثاني يوجعني",
        quick_1: "لقد أُصبت",
        quick_2: "بطني يوجعني",
        quick_3: "رأسي يوجعني",
        quick_4: "حرارتي مرتفعة",
        quick_5: "أنفي ينزف",
        quick_6: "أريد أن أستفرغ",
        front: "الأمام",
        back: "الخلف",
        idk: "لا أعرف",
        part_head: "الرأس",
        part_eye: "العين",
        part_ear: "الأذن",
        part_nose: "الأنف",
        part_mouth: "الفم / الأسنان",
        part_neck: "الرقبة",
        part_chest: "الصدر",
        part_belly: "البطن",
        part_arm: "الذراع / اليد",
        part_leg: "الساق / القدم",
        part_back: "الظهر",
        part_skin: "الجلد",
        part_whole: "كل الجسم",
        side_select_arm: "أي ذراع؟",
        side_select_leg: "أي ساق؟",
        side_left: "اليسار",
        side_right: "اليمين",
        side_both: "كلاهما",
        belly_top: "أعلى البطن",
        belly_navel: "حول السرة",
        belly_bottom: "أسفل البطن",
        belly_right_bottom: "أسفل البطن يميناً",
        arm_upper: "الكتف",
        arm_lower: "الكوع",
        arm_hand: "اليد",
        leg_thigh: "الفخذ",
        leg_knee: "الركبة",
        leg_calf: "الساق / الكاحل",
        leg_foot: "القدم",
        hurt_how: "كيف أصبت؟",
        hurt_state: "كيف حالك الآن؟",
        hurt_1: "وقعت",
        hurt_2: "اصطدمت",
        hurt_3: "أنجرحت",
        hurt_4: "التوى",
        state_1: "ينزل دم",
        state_2: "منفوخ",
        state_3: "فيها كدمة",
        state_4: "يوجعني لما أتحرك",
        head_q: "هل تشعر بدوخة أو تريد أن تستفرغ؟",
        yes: "نعم",
        no: "لا",        follow_belly: "هل أكلت؟",
        follow_fever: "هل أخذت دواء؟",
        follow_vomit: "كم مرة استفرغت؟",
        vomit_1: "مرة واحدة",
        vomit_2: "مرتان",
        vomit_3: "3 مرات أو أكثر",
        allergy_title: "هل لديك حساسية؟",
        allergy_none: "لا يوجد",
        allergy_drug: "الدواء",
        allergy_peanut: "الفول السوداني / المكسرات",
        allergy_milk: "الحليب",
        allergy_egg: "البيض",
        allergy_seafood: "المأكولات البحرية",
        allergy_peach: "الخوخ",
        allergy_wheat: "القمح",
        med_title: "هل تأخذ أي دواء؟", med_none: "لا", med_cold: "دواء برد", med_pain: "مسكن", med_digest: "دواء هضم", med_hospital: "دواء من المستشفى", med_idk: "لا أعرف", summary_med_info: "💊 الأدوية الحالية", summary_med_label: "الأدوية",
        arm_left_all: "الذراع اليسرى كاملة", arm_right_all: "الذراع اليمنى كاملة", arm_left_mid: "الكوع الأيسر·الساعد", arm_right_mid: "الكوع الأيمن·الساعد", arm_left_bot: "اليد اليسرى·المعصم", arm_right_bot: "اليد اليمنى·المعصم", arm_left_multi: "الذراع اليسرى (متعدد)", arm_right_multi: "الذراع اليمنى (متعدد)",
        allergy_voice: "أخرى (تحدث)",
        med_title: "هل تأخذ أي دواء؟", med_none: "لا", med_cold: "دواء برد", med_pain: "مسكن", med_digest: "دواء هضم", med_hospital: "دواء من المستشفى", med_idk: "لا أعرف", summary_med_info: "💊 الأدوية الحالية", summary_med_label: "الأدوية",
        arm_left_all: "الذراع اليسرى كاملة", arm_right_all: "الذراع اليمنى كاملة", arm_left_mid: "الكوع الأيسر·الساعد", arm_right_mid: "الكوع الأيمن·الساعد", arm_left_bot: "اليد اليسرى·المعصم", arm_right_bot: "اليد اليمنى·المعصم", arm_left_multi: "الذراع اليسرى (متعدد)", arm_right_multi: "الذراع اليمنى (متعدد)",
        allergy_voice: "أخرى (تحدث)",
        nurse_mode: "وضع الممرضة",
        pin_prompt: "أدخل الرمز:",
        no_records: "لا توجد سجلات.",
        delete: "حذف",
        summary_title: "ملخص الذكاء الاصطناعي",
        error_api: "خطأ في إنشاء الملخص.",
        summary_symptom: "الأعراض",
        summary_part: "الجزء",
        summary_symptom_label: "الأعراض",
        summary_pain: "مستوى الألم",
        summary_time: "وقت البدء",
        summary_allergy_info: "🏥 معلومات الحساسية",
        summary_allergy_label: "الحساسية",
        pain_min: "لا يوجعني",
        pain_max: "يوجعني كثيراً",
        btn_start_over: "البدء من جديد",
        popup_success: "تم الإرسال بنجاح!",
        popup_desc: "تم الإرسال إلى المعلم.",
        belly_chest: "الصدر", profile_title: "أدخل بياناتك", profile_grade: "الصف", profile_class: "الفصل", profile_number: "الرقم", profile_name: "الاسم", profile_placeholder: "اكتب", profile_next: "التالي"
    },
  };
  
  const tts_codes = { ko: "ko-KR", en: "en-US", zh: "zh-CN", ru: "ru-RU", vi: "vi-VN", ja: "ja-JP", tl: "tl-PH", km: "km-KH", th: "th-TH", mn: "mn-MN", uz: "uz-UZ", ar: "ar-SA" };
  
  const symptomsData = {
    "머리": [
      { id: "s1", icon: "🤕", ko: "지끈지끈 아파요", en: "Throbbing headache", zh: "一阵阵地疼", ru: "Пульсирующая боль", vi: "Đau nhức", ja: "ズキズキする", tl: "Sumasakit ang ulo", km: "ក្បាលខ្ញុំលោតឌឹបៗ", th: "หนู/ผมปวดหัวตุบๆ", mn: "Миний толгой лугшиж өвдөж байна", uz: "Boshim loqillab og'riyapti", ar: "رأسي يوجعني بقوة" },
      { id: "s2", icon: "💫", ko: "어지러워요", en: "Dizzy", zh: "头晕", ru: "Кружится голова", vi: "Chóng mặt", ja: "めまいがする", tl: "Nahihilo", km: "ខ្ញុំវិលមុខ", th: "หนู/ผมเวียนหัว", mn: "Миний толгой эргэж байна", uz: "Boshim aylanyapti", ar: "أشعر بدوخة" },
      { id: "s3", icon: "💥", ko: "부딪혔어요", en: "Bumped my head", zh: "撞到了", ru: "Ударился(лась)", vi: "Bị va đập", ja: "あたまをぶつけた", tl: "Nauntog", km: "ខ្ញុំបុកក្បាល", th: "หัวไปกระแทกมา", mn: "Би толгойгоо мөргөчихлөө", uz: "Boshimni urib oldim", ar: "ضربت رأسي" },
      { id: "s4", icon: "😵‍💫", ko: "멍해요", en: "Feeling dazed", zh: "发呆", ru: "В ступоре", vi: "Choáng váng", ja: "ぼーっとする", tl: "Tulala", km: "ខ្ញុំវង្វេងវង្វាន់", th: "หนู/ผมรู้สึกมึนงง", mn: "Би манарч байна", uz: "Boshim qotib qoldi", ar: "رأسي ثقيل" }
    ],
    "팔·손": [
      { id: "ag1", icon: "🩹", ko: "긁히고 까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tirnaldi", ar: "انخدش" },
      { id: "ag2", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيه كدمة" },
      { id: "ag3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "ag4", icon: "⚡", ko: "삐었어요", en: "Sprained", zh: "扭伤", ru: "Растяжение", vi: "Bong gân", ja: "ひねった", tl: "Napilay", km: "ខ្ញុំគ្រេច", th: "เคล็ดขัดยอก", mn: "Би булгалчихсан", uz: "Qayirib oldim", ar: "التوى" },
      { id: "ag5", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" },
      { id: "ag6", icon: "😣", ko: "움직이면 아파요", en: "Hurts when moving", zh: "动就疼", ru: "Больно двигать", vi: "Đau khi cử động", ja: "うごかすといたい", tl: "Masakit pag ginalaw", km: "វាឈឺនៅពេលខ្ញុំកម្រើក", th: "ขยับแล้วเจ็บ", mn: "Хөдлөхөөр өвдөж байна", uz: "Qimirlatsam og'riyapti", ar: "يوجعني لما أتحرك" }
    ],
    "다리·발": [
      { id: "lg1", icon: "🩹", ko: "까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ជើង", th: "หนู/ผมมีแผลถลอกที่ขา", mn: "Миний хөл шалбарчихсан", uz: "Tirnaldi", ar: "انخدش" },
      { id: "lg2", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំជើង", th: "หนู/ผมมีรอยฟกช้ำที่ขา", mn: "Миний хөл хөхөрчихсөн", uz: "Ko'kardi", ar: "فيه كدمة" },
      { id: "lg3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើមជើង", th: "ขาหนู/ผมบวม", mn: "Миний хөл хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "lg4", icon: "⚡", ko: "삐었어요", en: "Sprained", zh: "扭伤", ru: "Растяжение", vi: "Bong gân", ja: "ひねった", tl: "Napilay", km: "ខ្ញុំគ្រេចជើង", th: "ขาหนู/ผมเคล็ดขัดยอก", mn: "Миний хөл булгарчихсан", uz: "Qayirib oldim", ar: "التوى" },
      { id: "lg5", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាមជើង", th: "หนู/ผมเลือดไหลที่ขา", mn: "Миний хөлнөөс цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" },
      { id: "lg6", icon: "🚶", ko: "걸으면 아파요", en: "Hurts to walk", zh: "走路疼", ru: "Больно ходить", vi: "Đau khi đi", ja: "あるくといたい", tl: "Masakit maglakad", km: "វាឈឺនៅពេលខ្ញុំដើរ", th: "เดินแล้วเจ็บ", mn: "Алхахаар өвдөж байна", uz: "Yursam og'riyapti", ar: "يوجعني لما أمشي" }
    ],
    "눈": [
      { id: "e1", icon: "🫣", ko: "가려워요", en: "Itchy", zh: "痒", ru: "Чешется", vi: "Ngứa", ja: "かゆい", tl: "Makati", km: "ភ្នែកខ្ញុំរមាស់", th: "หนู/ผมคันตา", mn: "Миний нүд загатнаж байна", uz: "Qichishyapti", ar: "تحكني" },
      { id: "e2", icon: "👁️", ko: "아파요", en: "Hurts", zh: "疼", ru: "Болит", vi: "Đau", ja: "いたい", tl: "Masakit", km: "ភ្នែកខ្ញុំឈឺ", th: "หนู/ผมเจ็บตา", mn: "Миний нүд өвдөж байна", uz: "Og'riyapti", ar: "توجعني" },
      { id: "e3", icon: "🩸", ko: "빨개요", en: "Red", zh: "红了", ru: "Покраснел", vi: "Đỏ", ja: "あかい", tl: "Mapula", km: "ភ្នែកខ្ញុំក្រហម", th: "ตาหนู/ผมแดง", mn: "Миний нүд улайчихсан", uz: "Qizarib ketdi", ar: "حمراء" },
      { id: "e4", icon: "😭", ko: "뭐가 들어갔어요", en: "Something got in", zh: "进了东西", ru: "Что-то попало", vi: "Có gì vào mắt", ja: "なにかはいった", tl: "May pumasok sa mata", km: "មានអ្វីចូលភ្នែកខ្ញុំ", th: "มีอะไรเข้าตาหนู/ผม", mn: "Нүд рүү юм орчихлоо", uz: "Ko'zimga nimadir kirdi", ar: "دخل شيء في عيني" }
    ],
    "귀": [
      { id: "ea1", icon: "👂", ko: "아파요", en: "Hurts", zh: "疼", ru: "Болит", vi: "Đau", ja: "いたい", tl: "Masakit", km: "ត្រចៀកខ្ញុំឈឺ", th: "หนู/ผมเจ็บหู", mn: "Миний чих өвдөж байна", uz: "Og'riyapti", ar: "توجعني" },
      { id: "ea2", icon: "🙉", ko: "잘 안 들려요", en: "Can't hear well", zh: "听不清", ru: "Плохо слышу", vi: "Nghe không rõ", ja: "よくきこえない", tl: "Hindi makarinig ng maayos", km: "ខ្ញុំស្តាប់មិនសូវឮទេ", th: "หนู/ผมไม่ได้ยินชัด", mn: "Би сайн сонсохгүй байна", uz: "Yaxshi eshitmayapman", ar: "لا أسمع جيداً" },
      { id: "ea3", icon: "🔔", ko: "소리가 나요", en: "Ringing sound", zh: "耳鸣", ru: "Шум в ушах", vi: "Ù tai", ja: "ピーっとおとがする", tl: "May tumutunog", km: "ខ្ញុំឮសំឡេងក្នុងត្រចៀក", th: "หนู/ผมได้ยินเสียงวิ้งๆในหู", mn: "Миний чих шуугиж байна", uz: "Qulog'im shang'illayapti", ar: "أسمع صوتاً في أذني" }
    ],
    "코": [
      { id: "n1", icon: "💧", ko: "콧물이 나요", en: "Runny nose", zh: "流鼻涕", ru: "Насморк", vi: "Chảy nước mũi", ja: "はなみずがでる", tl: "Tumutulo ang sipon", km: "ខ្ញុំហៀរសំបោរ", th: "หนู/ผมมีน้ำมูกไหล", mn: "Миний нус гоожиж байна", uz: "Burnim oqayapti", ar: "أنفي يسيل" },
      { id: "n2", icon: "🤧", ko: "막혔어요", en: "Stuffy nose", zh: "鼻塞", ru: "Заложен нос", vi: "Nghẹt mũi", ja: "はながつまる", tl: "Barado ang ilong", km: "ខ្ញុំតឹងច្រមុះ", th: "หนู/ผมคัดจมูก", mn: "Миний хамар битүүрчихсэн", uz: "Burnim bitdi", ar: "أنفي مسدود" },
      { id: "n3", icon: "🩸", ko: "코피가 나요", en: "Nosebleed", zh: "流鼻血", ru: "Кровь из носа", vi: "Chảy máu cam", ja: "はなぢがでる", tl: "Dumudugo ang ilong", km: "ខ្ញុំហូរឈាមច្រមុះ", th: "หนู/ผมเลือดกำเดาไหล", mn: "Миний хамарнаас цус гарч байна", uz: "Burnimdan qon kelyapti", ar: "أنفي ينزف" },
      { id: "n4", icon: "💨", ko: "재채기가 나요", en: "Sneezing", zh: "打喷嚏", ru: "Чихаю", vi: "Hắt hơi", ja: "くしゃみがでる", tl: "Bumabahin", km: "ខ្ញុំកណ្តាស់", th: "หนู/ผมจาม", mn: "Би найтааж байна", uz: "Aksa uryapman", ar: "أعطس" }
    ],
    "입·이": [
      { id: "m1", icon: "🦷", ko: "이가 아파요", en: "Toothache", zh: "牙疼", ru: "Болит зуб", vi: "Đau răng", ja: "はがいたい", tl: "Masakit ang ngipin", km: "ខ្ញុំឈឺធ្មេញ", th: "หนู/ผมปวดฟัน", mn: "Миний шүд өвдөж байна", uz: "Tishim og'riyapti", ar: "أسناني توجعني" },
      { id: "m2", icon: "〰️", ko: "이가 흔들려요", en: "Loose tooth", zh: "牙齿松动", ru: "Шатается зуб", vi: "Răng lung lay", ja: "はがぐらぐらする", tl: "Umuuga ang ngipin", km: "ធ្មេញខ្ញុំរង្គើ", th: "ฟันหนู/ผมโยก", mn: "Миний шүд хөдөлж байна", uz: "Tishim qimirlayapti", ar: "سني يتحرك" },
      { id: "m3", icon: "👅", ko: "입안이 헐었어요", en: "Mouth sore", zh: "口腔溃疡", ru: "Язвочка во рту", vi: "Lở miệng", ja: "くちのなかがいたい", tl: "May singaw", km: "ខ្ញុំឈឺក្នុងមាត់", th: "หนู/ผมเจ็บในปาก", mn: "Миний ам өвдөж байна", uz: "Og'zim yaralandi", ar: "فمي مجروح" }
    ],
    "목": [
      { id: "nk1", icon: "😫", ko: "삼킬 때 아파요", en: "Hurts to swallow", zh: "吞咽时疼", ru: "Больно глотать", vi: "Nuốt đau", ja: "のみこむといたい", tl: "Masakit lumunok", km: "ខ្ញុំឈឺពេលលេប", th: "กลืนแล้วเจ็บ", mn: "Залгихад өвдөж байна", uz: "Yutunsam og'riyapti", ar: "يوجعني لما أبلع" },
      { id: "nk2", icon: "😷", ko: "기침이 나요", en: "Coughing", zh: "咳嗽", ru: "Кашель", vi: "Ho", ja: "せきがでる", tl: "Inuubo", km: "ខ្ញុំក្អក", th: "หนู/ผมไอ", mn: "Би ханиалгаж байна", uz: "Yötalyapman", ar: "عندي كحة" },
      { id: "nk3", icon: "🤐", ko: "목소리가 안 나와요", en: "Lost my voice", zh: "发不出声音", ru: "Пропал голос", vi: "Mất tiếng", ja: "こえがでない", tl: "Nawalan ng boses", km: "ខ្ញុំបាត់សំឡេង", th: "หนู/ผมไม่มีเสียง", mn: "Миний хоолой сөөчихсөн", uz: "Ovozim chiqmayapti", ar: "صوتي لا يخرج" },
      { id: "nk4", icon: "🙅", ko: "목을 못 돌려요", en: "Can't turn neck", zh: "脖子转不了", ru: "Не могу повернуть шею", vi: "Không quay được cổ", ja: "くびがまわらない", tl: "Hindi malingon ang leeg", km: "ខ្ញុំងាកកមិនរួចទេ", th: "หนู/ผมหันคอไม่ได้", mn: "Би хүзүүгээ эргүүлж чадахгүй байна", uz: "Bo'ynimni bura olmayapman", ar: "لا أستطيع لف رقبتي" }
    ],
    "가슴": [
      { id: "c1", icon: "😮‍💨", ko: "숨쉬기 힘들어요", en: "Hard to breathe", zh: "呼吸困难", ru: "Трудно дышать", vi: "Khó thở", ja: "いきがくるしい", tl: "Hirap huminga", km: "ខ្ញុំពិបាកដកដង្ហើម", th: "หนู/ผมหายใจไม่ออก", mn: "Амьсгалахад хэцүү байна", uz: "Nafas olishga qiynalyapman", ar: "لا أستطيع التنفس جيداً" },
      { id: "c2", icon: "⚡", ko: "콕콕 아파요", en: "Sharp pain", zh: "刺痛", ru: "Колющая боль", vi: "Đau nhói", ja: "チクチクいたい", tl: "May tumutusok na sakit", km: "ខ្ញុំចាក់ចុកក្នុងទ្រូង", th: "หนู/ผมเจ็บจี๊ดๆที่หน้าอก", mn: "Цээжээр хатгуулж өвдөж байна", uz: "Sanchib og'riyapti", ar: "يوجعني مثل الإبرة" },
      { id: "c3", icon: "💓", ko: "두근거려요", en: "Heart pounding", zh: "心跳加速", ru: "Сердце колотится", vi: "Tim đập nhanh", ja: "ドキドキする", tl: "Mabilis ang tibok ng puso", km: "បេះដូងខ្ញុំលោតញាប់", th: "หัวใจหนู/ผมเต้นแรง", mn: "Миний зүрх дэлсэж байна", uz: "Yuragim dukkillayapti", ar: "قلبي يدق بسرعة" },
      { id: "c4", icon: "🧱", ko: "답답해요", en: "Feels tight", zh: "胸闷", ru: "Давит в груди", vi: "Tức ngực", ja: "むねがくるしい", tl: "Naninikip ang dibdib", km: "ខ្ញុំតឹងទ្រូង", th: "หนู/ผมรู้สึกอึดอัดหน้าอก", mn: "Цээж давчдаж байна", uz: "Nafasim qisyapti", ar: "صدري ضيق" }
    ],
        "배": [
      { id: "b1", icon: "⚡", ko: "콕콕 찔러요", en: "Sharp stinging", zh: "刺痛", ru: "Колет", vi: "Đau nhói", ja: "チクチクいたい", tl: "May tumutusok na sakit", km: "ខ្ញុំចាក់ចុកក្នុងពោះ", th: "หนู/ผมเจ็บจี๊ดๆที่ท้อง", mn: "Гэдэс хатгуулж өвдөж байна", uz: "Sanchib og'riyapti", ar: "يوجعني مثل الإبرة" },
      { id: "b2", icon: "🌪️", ko: "쥐어짜듯 아파요", en: "Cramping pain", zh: "绞痛", ru: "Крутит живот", vi: "Đau quặn", ja: "ギュッといたい", tl: "Namimilipit sa sakit", km: "ខ្ញុំរមួលពោះ", th: "หนู/ผมปวดบิดๆที่ท้อง", mn: "Гэдэс базлаж өвдөж байна", uz: "Buralib og'riyapti", ar: "بطني يمغصني" },
      { id: "b3", icon: "🤢", ko: "토할 것 같아요", en: "Feel like vomiting", zh: "想吐", ru: "Тошнит", vi: "Buồn nôn", ja: "きもちわるい", tl: "Gusto kong sumuka", km: "ខ្ញុំចង់ក្អួត", th: "หนู/ผมอยากอ้วก", mn: "Би бөөлжмөөр байна", uz: "Ko'nglim ayniyapti", ar: "أريد أن أستفرغ" },
      { id: "b6", icon: "😵", ko: "체한 것 같아요", en: "Upset stomach", zh: "消化不良", ru: "Расстройство желудка", vi: "Khó tiêu", ja: "胃もたれがする", tl: "Hindi natunawan", km: "ពិបាករំលាយអាហារ", th: "อาหารไม่ย่อย", mn: "Ходоод эвгүйрхэх", uz: "Ovqat hazm bo'lmayapti", ar: "سوء هضم" },
      { id: "b4", icon: "💩", ko: "설사했어요", en: "Diarrhea", zh: "拉肚子", ru: "Понос", vi: "Tiêu chảy", ja: "げりをした", tl: "Nagtatae", km: "ខ្ញុំរាក", th: "หนู/ผมท้องเสีย", mn: "Миний гэдэс гүйлгэж байна", uz: "Ichim ketyapti", ar: "عندي إسهال" },
      { id: "b5", icon: "🚽", ko: "화장실 못 갔어요", en: "Can't go to bathroom", zh: "上不了厕所", ru: "Не могу сходить в туалет", vi: "Không đi vệ sinh được", ja: "うんちがでない", tl: "Hindi makatae", km: "ខ្ញុំមិនអាចទៅបន្ទប់ទឹកបានទេ", th: "หนู/ผมไปเข้าห้องน้ำไม่ได้", mn: "Би бие засаж чадахгүй байна", uz: "Hojatxonaga bora olmadim", ar: "لا أستطيع دخول الحمام" }
    ],
    "윗배": [
      { id: "b1", icon: "⚡", ko: "콕콕 찔러요", en: "Sharp stinging", zh: "刺痛", ru: "Колет", vi: "Đau nhói", ja: "チクチクいたい", tl: "May tumutusok na sakit", km: "ខ្ញុំចាក់ចុកក្នុងពោះ", th: "หนู/ผมเจ็บจี๊ดๆที่ท้อง", mn: "Гэдэс хатгуулж өвдөж байна", uz: "Sanchib og'riyapti", ar: "يوجعني مثل الإبرة" },
      { id: "b2", icon: "🌪️", ko: "쥐어짜듯 아파요", en: "Cramping pain", zh: "绞痛", ru: "Крутит живот", vi: "Đau quặn", ja: "ギュッといたい", tl: "Namimilipit sa sakit", km: "ខ្ញុំរមួលពោះ", th: "หนู/ผมปวดบิดๆที่ท้อง", mn: "Гэдэс базлаж өвдөж байна", uz: "Buralib og'riyapti", ar: "بطني يمغصني" },
      { id: "b3", icon: "🤢", ko: "토할 것 같아요", en: "Feel like vomiting", zh: "想吐", ru: "Тошнит", vi: "Buồn nôn", ja: "きもちわるい", tl: "Gusto kong sumuka", km: "ខ្ញុំចង់ក្អួត", th: "หนู/ผมอยากอ้วก", mn: "Би бөөлжмөөр байна", uz: "Ko'nglim ayniyapti", ar: "أريد أن أستفرغ" },
      { id: "b6", icon: "😵", ko: "체한 것 같아요", en: "Upset stomach", zh: "消化不良", ru: "Расстройство желудка", vi: "Khó tiêu", ja: "胃もたれがする", tl: "Hindi natunawan", km: "ពិបាករំលាយអាហារ", th: "อาหารไม่ย่อย", mn: "Ходоод эвгүйрхэх", uz: "Ovqat hazm bo'lmayapti", ar: "سوء هضم" }
    ],
    "아랫배": [
      { id: "b1", icon: "⚡", ko: "콕콕 찔러요", en: "Sharp stinging", zh: "刺痛", ru: "Колет", vi: "Đau nhói", ja: "チクチクいたい", tl: "May tumutusok na sakit", km: "ខ្ញុំចាក់ចុកក្នុងពោះ", th: "หนู/ผมเจ็บจี๊ดๆที่ท้อง", mn: "Гэдэс хатгуулж өвдөж байна", uz: "Sanchib og'riyapti", ar: "يوجعني مثل الإبرة" },
      { id: "b2", icon: "🌪️", ko: "쥐어짜듯 아파요", en: "Cramping pain", zh: "绞痛", ru: "Крутит живот", vi: "Đau quặn", ja: "ギュッといたい", tl: "Namimilipit sa sakit", km: "ខ្ញុំរមួលពោះ", th: "หนู/ผมปวดบิดๆที่ท้อง", mn: "Гэдэс базлаж өвдөж байна", uz: "Buralib og'riyapti", ar: "بطني يمغصني" },
      { id: "b4", icon: "💩", ko: "설사했어요", en: "Diarrhea", zh: "拉肚子", ru: "Понос", vi: "Tiêu chảy", ja: "げりをした", tl: "Nagtatae", km: "ខ្ញុំរាក", th: "หนู/ผมท้องเสีย", mn: "Миний гэдэс гүйлгэж байна", uz: "Ichim ketyapti", ar: "عندي إسهال" },
      { id: "b5", icon: "🚽", ko: "화장실 못 갔어요", en: "Can't go to bathroom", zh: "上不了厕所", ru: "Не могу сходить в туалет", vi: "Không đi vệ sinh được", ja: "うんちがでない", tl: "Hindi makatae", km: "ខ្ញុំមិនអាចទៅបន្ទប់ទឹកបានទេ", th: "หนู/ผมไปเข้าห้องน้ำไม่ได้", mn: "Би бие засаж чадахгүй байна", uz: "Hojatxonaga bora olmadim", ar: "لا أستطيع دخول الحمام" }
    ],
    "어깨·윗팔": [
      { id: "au1", icon: "💫", ko: "어깨가 아파요", en: "Shoulder hurts", zh: "肩膀疼", ru: "Болит плечо", vi: "Đau vai", ja: "かたがいたい", tl: "Masakit ang balikat", km: "ខ្ញុំឈឺស្មា", th: "หนู/ผมเจ็บไหล่", mn: "Миний мөр өвдөж байна", uz: "Yelkam og'riyapti", ar: "كتفي يوجعني" },
      { id: "au2", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيه كدمة" },
      { id: "au3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "au4", icon: "😵‍💫", ko: "팔을 못 들겠어요", en: "Can't lift arm", zh: "抬不起胳膊", ru: "Не могу поднять руку", vi: "Không nâng được tay", ja: "うでがあがらない", tl: "Hindi mabuhat ang braso", km: "ខ្ញុំលើកដៃមិនរួចទេ", th: "หนู/ผมยกแขนไม่ขึ้น", mn: "Би гараа өргөж чадахгүй байна", uz: "Qo'limni ko'tara olmayapman", ar: "لا أستطيع رفع يدي" },
      { id: "au5", icon: "😣", ko: "움직이면 아파요", en: "Hurts when moving", zh: "动就疼", ru: "Больно двигать", vi: "Đau khi cử động", ja: "うごかすといたい", tl: "Masakit pag ginalaw", km: "វាឈឺនៅពេលខ្ញុំកម្រើក", th: "ขยับแล้วเจ็บ", mn: "Хөдлөхөөр өвдөж байна", uz: "Qimirlatsam og'riyapti", ar: "يوجعني لما أتحرك" }
    ],
    "팔꿈치·아랫팔": [
      { id: "al1", icon: "🩹", ko: "긁히고 까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tirnaldi", ar: "انخدش" },
      { id: "al2", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيه كدمة" },
      { id: "al3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "al4", icon: "⚡", ko: "굽힐 때 아파요", en: "Hurts to bend", zh: "弯曲时疼", ru: "Больно сгибать", vi: "Đau khi gập", ja: "まげるといたい", tl: "Masakit pag tinupi", km: "វាឈឺនៅពេលខ្ញុំបត់កែងដៃ", th: "งอแล้วเจ็บ", mn: "Нугалахаар өвдөж байна", uz: "Buksak og'riyapti", ar: "يوجعني لما أثنيه" },
      { id: "al5", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" }
    ],
    "손·손목": [
      { id: "ah1", icon: "🩹", ko: "긁히고 까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tirnaldi", ar: "انخدش" },
      { id: "ah2", icon: "⚡", ko: "손목을 삐었어요", en: "Sprained wrist", zh: "手腕扭伤", ru: "Растянул(а) запястье", vi: "Bong gân cổ tay", ja: "てくびをひねった", tl: "Napilay ang pulso", km: "ខ្ញុំគ្រេចកដៃ", th: "หนู/ผมข้อมือเคล็ด", mn: "Миний бугуй булгарчихсан", uz: "Bilagimni qayirib oldim", ar: "التوى معصمي" },
      { id: "ah3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "ah4", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" },
      { id: "ah5", icon: "😣", ko: "움직이면 아파요", en: "Hurts when moving", zh: "动就疼", ru: "Больно двигать", vi: "Đau khi cử động", ja: "うごかすといたい", tl: "Masakit pag ginalaw", km: "វាឈឺនៅពេលខ្ញុំកម្រើក", th: "ขยับแล้วเจ็บ", mn: "Хөдлөхөөр өвдөж байна", uz: "Qimirlatsam og'riyapti", ar: "يوجعني لما أتحرك" },
      { id: "ah6", icon: "🫐", ko: "손가락이 끼였어요", en: "Finger got caught", zh: "手指夹到了", ru: "Прищемил(а) палец", vi: "Kẹt ngón tay", ja: "ゆびをはさんだ", tl: "Naipit ang daliri", km: "ខ្ញុំគៀបម្រាមដៃ", th: "หนู/ผมโดนหนีบนิ้ว", mn: "Миний хуруу хавчуулагдчихсан", uz: "Barmog'im qisilib qoldi", ar: "انحشر إصبعي" }
    ],
    "팔꿈치": [
      { id: "al1", icon: "🩹", ko: "긁히고 까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tirnaldi", ar: "انخدش" },
      { id: "al2", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيه كدمة" },
      { id: "al3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "al4", icon: "⚡", ko: "굽힐 때 아파요", en: "Hurts to bend", zh: "弯曲时疼", ru: "Больно сгибать", vi: "Đau khi gập", ja: "まげるといたい", tl: "Masakit pag tinupi", km: "វាឈឺនៅពេលខ្ញុំបត់កែងដៃ", th: "งอแล้วเจ็บ", mn: "Нугалахаар өвдөж байна", uz: "Buksak og'riyapti", ar: "يوجعني لما أثنيه" },
      { id: "al5", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" }
    ],
    "아랫팔": [
      { id: "al1", icon: "🩹", ko: "긁히고 까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tirnaldi", ar: "انخدش" },
      { id: "al2", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيه كدمة" },
      { id: "al3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "al5", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" }
    ],
    "손목": [
      { id: "ah1", icon: "🩹", ko: "긁히고 까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tirnaldi", ar: "انخدش" },
      { id: "ah2", icon: "⚡", ko: "손목을 삐었어요", en: "Sprained wrist", zh: "手腕扭伤", ru: "Растянул(а) запястье", vi: "Bong gân cổ tay", ja: "てくびをひねった", tl: "Napilay ang pulso", km: "ខ្ញុំគ្រេចកដៃ", th: "หนู/ผมข้อมือเคล็ด", mn: "Миний бугуй булгарчихсан", uz: "Bilagimni qayirib oldim", ar: "التوى معصمي" },
      { id: "ah3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "ah4", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" },
      { id: "ah5", icon: "😣", ko: "움직이면 아파요", en: "Hurts when moving", zh: "动就疼", ru: "Больно двигать", vi: "Đau khi cử động", ja: "うごかすといたい", tl: "Masakit pag ginalaw", km: "វាឈឺនៅពេលខ្ញុំកម្រើក", th: "ขยับแล้วเจ็บ", mn: "Хөдлөхөөр өвдөж байна", uz: "Qimirlatsam og'riyapti", ar: "يوجعني لما أتحرك" }
    ],
    "손": [
      { id: "ah1", icon: "🩹", ko: "긁히고 까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tirnaldi", ar: "انخدش" },
      { id: "ah3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "ah4", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" },
      { id: "ah5", icon: "😣", ko: "움직이면 아파요", en: "Hurts when moving", zh: "动就疼", ru: "Больно двигать", vi: "Đau khi cử động", ja: "うごかすといたい", tl: "Masakit pag ginalaw", km: "វាឈឺនៅពេលខ្ញុំកម្រើក", th: "ขยับแล้วเจ็บ", mn: "Хөдлөхөөр өвдөж байна", uz: "Qimirlatsam og'riyapti", ar: "يوجعني لما أتحرك" },
      { id: "ah6", icon: "🫐", ko: "손가락이 끼였어요", en: "Finger got caught", zh: "手指夹到了", ru: "Прищемил(а) палец", vi: "Kẹt ngón tay", ja: "ゆびをはさんだ", tl: "Naipit ang daliri", km: "ខ្ញុំគៀបម្រាមដៃ", th: "หนู/ผมโดนหนีบนิ้ว", mn: "Миний хуруу хавчуулагдчихсан", uz: "Barmog'im qisilib qoldi", ar: "انحشر إصبعي" }
    ],
    "허벅지": [
      { id: "lt1", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيه كدمة" },
      { id: "lt2", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "lt3", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" },
      { id: "lt4", icon: "🩹", ko: "긁히고 까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tirnaldi", ar: "انخدش" },
      { id: "lt5", icon: "😣", ko: "움직이면 아파요", en: "Hurts when moving", zh: "动就疼", ru: "Больно двигать", vi: "Đau khi cử động", ja: "うごかすといたい", tl: "Masakit pag ginalaw", km: "វាឈឺនៅពេលខ្ញុំកម្រើក", th: "ขยับแล้วเจ็บ", mn: "Хөдлөхөөр өвдөж байна", uz: "Qimirlatsam og'riyapti", ar: "يوجعني لما أتحرك" }
    ],
    "무릎": [
      { id: "lk1", icon: "🩹", ko: "무릎이 까졌어요", en: "Scraped knee", zh: "膝盖擦伤了", ru: "Ссадина на колене", vi: "Trầy đầu gối", ja: "ひざをすりむいた", tl: "Nagasgas ang tuhod", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tizzam tirnaldi", ar: "ركبتي انخدشت" },
      { id: "lk2", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيها كدمة" },
      { id: "lk3", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخة" },
      { id: "lk4", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" },
      { id: "lk5", icon: "😵‍💫", ko: "굽히면 아파요", en: "Hurts to bend", zh: "弯曲时疼", ru: "Больно сгибать", vi: "Đau khi gập", ja: "まげるといたい", tl: "Masakit pag tinupi", km: "វាឈឺនៅពេលខ្ញុំបត់ជង្គង់", th: "งอเข่าแล้วเจ็บ", mn: "Өвдгөө нугалахаар өвдөж байна", uz: "Buksak og'riyapti", ar: "توجعني لما أثنيها" }
    ],
    "종아리·발목": [
      { id: "lc1", icon: "⚡", ko: "발목을 삐었어요", en: "Sprained ankle", zh: "扭伤脚踝", ru: "Подвернул(а) ногу", vi: "Bong gân mắt cá", ja: "あしくびをひねった", tl: "Napilay ang bukong-bukong", km: "ខ្ញុំគ្រេចកជើង", th: "หนู/ผมข้อเท้าพลิก", mn: "Миний шагай булгарчихсан", uz: "To'pig'imni qayirib oldim", ar: "التوى كاحلي" },
      { id: "lc2", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخ" },
      { id: "lc3", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيه كدمة" },
      { id: "lc4", icon: "🚶", ko: "걸으면 아파요", en: "Hurts to walk", zh: "走路疼", ru: "Больно ходить", vi: "Đau khi đi", ja: "あるくといたい", tl: "Masakit maglakad", km: "វាឈឺនៅពេលខ្ញុំដើរ", th: "เดินแล้วเจ็บ", mn: "Алхахаар өвдөж байна", uz: "Yursam og'riyapti", ar: "يوجعني لما أمشي" }
    ],
    "발": [
      { id: "lf1", icon: "🩹", ko: "까졌어요", en: "Scraped", zh: "擦伤了", ru: "Ссадина", vi: "Bị trầy", ja: "すりむいた", tl: "Nagasgas", km: "ខ្ញុំរលាត់ស្បែក", th: "หนู/ผมมีแผลถลอก", mn: "Би шалбалчихсан", uz: "Tirnaldi", ar: "انخدشت" },
      { id: "lf2", icon: "🎈", ko: "부었어요", en: "Swollen", zh: "肿了", ru: "Опухло", vi: "Sưng", ja: "はれている", tl: "Namamaga", km: "ខ្ញុំហើម", th: "มันบวม", mn: "Минийх хавдчихсан", uz: "Ishib ketdi", ar: "منفوخة" },
      { id: "lf3", icon: "🩸", ko: "피가 나요", en: "Bleeding", zh: "流血", ru: "Идёт кровь", vi: "Chảy máu", ja: "ちがでている", tl: "Dumudugo", km: "ខ្ញុំហូរឈាម", th: "เลือดไหล", mn: "Цус гарч байна", uz: "Qon kelyapti", ar: "ينزل دم" },
      { id: "lf4", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيها كدمة" },
      { id: "lf5", icon: "🫧", ko: "물집이 생겼어요", en: "Blister", zh: "起水泡了", ru: "Мозоль/волдырь", vi: "Phồng rộp", ja: "まめができた", tl: "May paltos", km: "ខ្ញុំមានពងទឹក", th: "หนู/ผมมีตุ่มพอง", mn: "Миний хөл цэврүүтчихсэн", uz: "Pufakcha chiqdi", ar: "ظهرت فقاعة ماء" }
    ],
    "등·허리": [
      { id: "bk1", icon: "⚡", ko: "아파요", en: "Hurts", zh: "疼", ru: "Болит", vi: "Đau", ja: "いたい", tl: "Masakit", km: "ខ្ញុំឈឺខ្នង", th: "หนู/ผมปวดหลัง", mn: "Миний нуруу өвдөж байна", uz: "Og'riyapti", ar: "يوجعني" },
      { id: "bk2", icon: "💥", ko: "부딪혔어요", en: "Bumped", zh: "撞到了", ru: "Ударился(лась)", vi: "Bị va đập", ja: "ぶつけた", tl: "Tumama", km: "ខ្ញុំបុកខ្នង", th: "หลังหนู/ผมไปกระแทกมา", mn: "Би нуруугаа мөргөчихсөн", uz: "Urib oldim", ar: "اصطدمت" },
      { id: "bk3", icon: "😣", ko: "허리를 못 펴겠어요", en: "Can't straighten back", zh: "直不起腰", ru: "Не могу разогнуться", vi: "Không duỗi được lưng", ja: "せなかがのばせない", tl: "Hindi maidiretso ang likod", km: "ខ្ញុំអោនមិនរួចទេ", th: "หนู/ผมยืดหลังไม่ได้", mn: "Би нуруугаа тэнийлгэж чадахгүй байна", uz: "Qaddimni rostlay olmayapman", ar: "لا أستطيع فرد ظهري" },
      { id: "bk4", icon: "🫐", ko: "멍이 들었어요", en: "Bruised", zh: "淤青了", ru: "Синяк", vi: "Bầm tím", ja: "あおあざができた", tl: "May pasa", km: "ខ្ញុំជាំ", th: "หนู/ผมมีรอยฟกช้ำ", mn: "Би хөхөрчихсөн", uz: "Ko'kardi", ar: "فيه كدمة" }
    ],
    "피부": [
      { id: "sk1", icon: "🤚", ko: "가려워요", en: "Itchy", zh: "痒", ru: "Чешется", vi: "Ngứa", ja: "かゆい", tl: "Makati", km: "ស្បែកខ្ញុំរមាស់", th: "หนู/ผมคันผิว", mn: "Миний арьс загатнаж байна", uz: "Qichishyapti", ar: "تحكني" },
      { id: "sk2", icon: "🔴", ko: "두드러기가 났어요", en: "Hives", zh: "起荨麻疹了", ru: "Крапивница", vi: "Nổi mề đay", ja: "じんましんがでた", tl: "May pantal", km: "ខ្ញុំចេញកន្ទួល", th: "หนู/ผมมีผื่นขึ้น", mn: "Миний биеэр юм туурчихсан", uz: "Toshma toshdi", ar: "ظهرت حبوب" },
      { id: "sk3", icon: "🔥", ko: "데었어요", en: "Burned", zh: "烫伤了", ru: "Обжёгся(лась)", vi: "Bị bỏng", ja: "やけどした", tl: "Napaso", km: "ខ្ញុំរលាក", th: "หนู/ผมโดนลวก", mn: "Би түлэгдчихсэн", uz: "Kuyib qoldi", ar: "احترق" },
      { id: "sk4", icon: "💧", ko: "물집이 생겼어요", en: "Blister", zh: "起水泡了", ru: "Мозоль/волдырь", vi: "Phồng rộp", ja: "まめができた", tl: "May paltos", km: "ខ្ញុំមានពងទឹក", th: "หนู/ผมมีตุ่มพอง", mn: "Миний бие дээр цэврүү гарсан", uz: "Pufakcha chiqdi", ar: "ظهرت فقاعة ماء" }
    ],
    "몸 전체": [
      { id: "w1", icon: "🤒", ko: "열이 나요", en: "Fever", zh: "发烧", ru: "Температура", vi: "Sốt", ja: "ねつがある", tl: "May lagnat", km: "ខ្ញុំក្តៅខ្លួន", th: "หนู/ผมตัวร้อน", mn: "Би халуурч байна", uz: "Isitmam chiqyapti", ar: "حرارتي مرتفعة" },
      { id: "w2", icon: "🥶", ko: "춥고 떨려요", en: "Cold and shivering", zh: "发冷发抖", ru: "Озноб", vi: "Lạnh run", ja: "さむくてふるえる", tl: "Nanginginig sa ginaw", km: "ខ្ញុំរងាហើយញាក់", th: "หนู/ผมหนาวสั่น", mn: "Би даарч чичирч байна", uz: "Sovqotyapman va qaltirayapman", ar: "أشعر بالبرد وأرتجف" },
      { id: "w3", icon: "🫠", ko: "기운이 없어요", en: "No energy", zh: "没力气", ru: "Нет сил", vi: "Mệt mỏi", ja: "げんきがない", tl: "Walang lakas", km: "ខ្ញុំអស់កម្លាំង", th: "หนู/ผมไม่มีแรงเลย", mn: "Надад ямар ч хүч алга", uz: "Madorim yo'q", ar: "ليس عندي طاقة" },
      { id: "w4", icon: "🥱", ko: "잠이 계속 와요", en: "Very sleepy", zh: "一直想睡觉", ru: "Всё время хочу спать", vi: "Buồn ngủ", ja: "ずっとねむい", tl: "Inaantok", km: "ខ្ញុំងងុយគេងណាស់", th: "หนู/ผมง่วงนอนมากๆ", mn: "Би маш их нойрмоглож байна", uz: "Uyqum kelyapti", ar: "أريد أن أنام كثيراً" },
      { id: "w5", icon: "🤕", ko: "온몸이 쑤셔요", en: "Body aches", zh: "全身酸痛", ru: "Ломит всё тело", vi: "Nhức mỏi toàn thân", ja: "からだがいたい", tl: "Masakit ang buong katawan", km: "ខ្ញុំឈឺពេញខ្លួន", th: "หนู/ผมปวดเมื่อยทั้งตัว", mn: "Миний бүх бие өвдөж байна", uz: "Hamma joyim og'riyapti", ar: "كل جسمي يوجعني" }
    ]
  };
  
  const evaluateEmergency = (entries) => {
    let flags = new Set();
    let allSymptoms = entries.flatMap(e => e.symptoms.map(s => s.ko || s)).join(" ");
    let maxPain = 0;
    entries.forEach(e => {
      if (e.painLevels) {
        Object.values(e.painLevels).forEach(p => {
          if (parseInt(p) > maxPain) maxPain = parseInt(p);
        });
      } else if (e.painLevel) {
        if (parseInt(e.painLevel) > maxPain) maxPain = parseInt(e.painLevel);
      }
    });
    
    entries.forEach(data => {
      const symptomsStr = data.symptoms.map(s => s.ko || s).join(" ");
      
      if (data.part === "머리" && data.hurtMethod && (data.headQ === "yes" || symptomsStr.includes("토할 것 같아요") || symptomsStr.includes("어지러워요"))) {
        flags.add("뇌진탕 의심");
      }
      if (data.part === "배" && data.bellyPos === "오른쪽 아래" && maxPain >= 8) {
        flags.add("충수염 의심");
      }
    });


    if (allSymptoms.includes("두드러기가 났어요") && allSymptoms.includes("숨쉬기 힘들어요")) {
      flags.add("알레르기 쇼크 의심");
    }
    if (allSymptoms.includes("숨쉬기 힘들어요")) {
      flags.add("호흡곤란 의심");
    }
    if (maxPain >= 8) {
      flags.add("고강도 통증");
    }
    
    return Array.from(flags);
  };

  // State Management Helpers
  function getState() {
      const defaultState = { lang: 'ko', part: null, bellyPos: null, hurtMethod: null, hurtState: null, headQ: null, symptoms: [], painLevels: {}, startTime: null, followups: [], previousEntries: [], headSubSelected: false };
      return JSON.parse(sessionStorage.getItem('medical_state')) || defaultState;
  }

  function saveState(state) {
      sessionStorage.setItem('medical_state', JSON.stringify(state));
  }

  function clearState() {
      sessionStorage.removeItem('medical_state');
  }

  // UI Helpers
  function translateKoToLang(koStr, lang) {
      if (!lang || lang === 'ko' || !koStr) return koStr;
      const tLang = translations[lang];
      const tKo = translations.ko;
      
      let result = koStr;
      // 1. 단일 부위 완전 일치 검사 (ex: "머리" -> "Head")
      for (const key in tKo) {
          if (tKo[key] === result && tLang[key]) return tLang[key];
      }
      
      // 1.5. 증상 딕셔너리 검사 (symptomsData)
      for (const part in symptomsData) {
          const list = symptomsData[part];
          for (const item of list) {
              if (item.ko === result && item[lang]) return item[lang];
          }
      }
      
      // 2. 복합 문자열 치환 (ex: "팔·손 (왼쪽 어깨·윗팔)" -> "Arm/Hand (Left Shoulder/Upper arm)")
      const keys = Object.keys(tKo).sort((a, b) => tKo[b].length - tKo[a].length);
      for (const key of keys) {
          if (tKo[key] && typeof tKo[key] === 'string' && tKo[key].length > 1) {
              // 치환 시 정규식으로 안전하게 바꿈
              result = result.split(tKo[key]).join(tLang[key] || tKo[key]);
          }
      }
      return result;
  }

  function applyLanguageToUI() {
      const state = getState();
      
      // 아랍어(ar) 우측 정렬(RTL) 레이아웃 적용
      if (state.lang === 'ar') {
          document.body.setAttribute('dir', 'rtl');
      } else {
          document.body.removeAttribute('dir');
      }

      document.querySelectorAll('[data-i18n]').forEach(el => {
          const key = el.getAttribute('data-i18n');
          if (translations[state.lang] && translations[state.lang][key]) {
              el.innerHTML = translations[state.lang][key];
          }
      });
  }

  function speak(text) {
      if (!window.speechSynthesis) return;
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = tts_codes[getState().lang] || "ko-KR";
      window.speechSynthesis.speak(utterance);
  }

  // Setup Common UI (Header, Speaker)
  document.addEventListener('DOMContentLoaded', () => {
      applyLanguageToUI();
      document.querySelectorAll('.btn-speaker').forEach(btn => {
          btn.addEventListener('click', (e) => {
              const textSpan = e.currentTarget.parentElement.querySelector('span[data-i18n]');
              if (textSpan) {
                  const key = textSpan.getAttribute('data-i18n');
                  speak(translations[getState().lang][key]);
              }
          });
      });
      const nurseBtn = document.getElementById('btn-nurse-lock');
      if (nurseBtn) {
          nurseBtn.addEventListener('click', () => {
              const pin = prompt(translations[getState().lang]?.pin_prompt || "비밀번호:");
              if (pin === "1234") window.location.href = 'nurse.html';
              else if (pin !== null) alert("비밀번호가 틀렸습니다.");
          });
      }
  });
